### ISSUE TITLE
Exception happened "RVCount doesn't match with EvaluationStack" when invokefunction claim after deploying Example.SmartContract.NFT example project

### ISSUE THREAD

**Issue by songb2** [neo-project/neo-devpack-dotnet#1013]
Steps to reproduce:

1. Use nccs to build the NFT example project https://github.com/neo-project/neo-devpack-dotnet/tree/master/examples/Example.SmartContract.NFT
2. Deploy it to the local testnet via neo-cli.exe `deploy SampleLootNFT.nef`
3. Invoke claim method via RPC according to the readme https://github.com/neo-project/neo-devpack-dotnet/blob/master/examples/Example.SmartContract.NFT/README.md,
```javascript
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "invokefunction",
    "params": [
        "0xb78af146bd7aa6870bc5e005bb1134d5d1bfd2dc",
        "claim",
        [
            {
                "type": "Integer",
                "value": "7772"
            }
        ],
        [
            {
                "account": "0x8af673c2769fed72659b17217365b5077c173d9c",
                "scopes": "CalledByEntry"
            }
        ]
    ]
}
``` 
It returns the exception response
```javascript
{
    "jsonrpc": "2.0",
    "id": 3,
    "result": {
        "script": "AVweEcAfDAVjbGFpbQwUsJ1bUx9rpl93pT83MzjHg+Ba0r5BYn1bUg==",
        "state": "FAULT",
        "gasconsumed": "8144790",
        "exception": "RVCount doesn't match with EvaluationStack",
        "notifications": [],
        "stack": []
    }
}
``` 
Invoke from GUI also has the same issue:
![image](https://github.com/neo-project/neo-devpack-dotnet/assets/3377632/7c3b2bc2-e325-4bce-929e-1eab8251f72d)

@Jim8y

**Comment by Jim8y** [comment]
I will check

**Comment by Jim8y** [comment]
@songb2 please checkout https://github.com/neo-project/neo-devpack-dotnet/pull/1014, this should address the problem for now. I will dig the fundamental problem in the compiler, but https://github.com/neo-project/neo-devpack-dotnet/pull/1014 should work for you.

**Comment by songb2** [comment]
@Jim8y Yes, I tested that the fix works.
