### ISSUE TITLE
Manifest permission compilation error

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-devpack-dotnet#1070]
@Jim8y there is a bug when compile source together, the manifest takes whole the permissions for each contract.

You can see that `Contract_ABIAttributes` haven't got this permission

https://github.com/neo-project/neo-devpack-dotnet/blob/752a11bbf0ac5a429b9f4bbace27025f590b9448/tests/Neo.Compiler.CSharp.TestContracts/Contract_ABIAttributes.cs#L6-L9

https://github.com/neo-project/neo-devpack-dotnet/blob/752a11bbf0ac5a429b9f4bbace27025f590b9448/tests/Neo.Compiler.CSharp.UnitTests/UnitTest_ABI_Attributes.cs#L15

it take it from https://github.com/neo-project/neo-devpack-dotnet/blob/752a11bbf0ac5a429b9f4bbace27025f590b9448/tests/Neo.Compiler.CSharp.TestContracts/Contract_ContractCall.cs#L5

When I changed the address of this contract, all the artifact's manifest was changed

**Comment by Jim8y** [comment]
will check
