### ISSUE TITLE
Need asm for neovm.

### ISSUE THREAD

**Issue by lightszero** [neo-project/neo-devpack-dotnet#108]
we had a asm

https://github.com/neo-project/neo-compiler/tree/master/neoa,but that project had be closed.

maybe create a project repository "neo-devpack-asm".

@erikzhang 

and I want to create a middle layer for compilers,like llvm.

maybe can create a project repository "neolinker",

all compilers just need to compiler code to a middle format,then call neolinker to get .avm

**Comment by igormcoelho** [comment]
@lightszero one alternative to re-write llvm is to simply adopt llvm via wasm... some time ago I experimented with converting C++ -> LLVM -> wasm, and I believe we can convert wasm to NeoVM.
So we could do: C++ -> LLVM -> wasm -> neovm.
Some prototype is here already: https://github.com/neoresearch/neodev-cpp

**Comment by lightszero** [comment]
@igormcoelho  I think llvm-> neovm is another project,that is useful too.
I just want create a compiler middlelayer for our self neo-devpack-dotnet and neo-devpack-java and python maybe.

**Comment by lightszero** [comment]
it looks like
```
Main()
{
    PUSH 1//push 1 number
    PUSH 2
    CALL method1
    RET;
}
method1()
{
label1：
    ADD
88:
    RET
}

```
