### ISSUE TITLE
Fix not covered contracts

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-devpack-dotnet#1080]
After migrate the whole tests to the new system, some contracts have been detected without any kind of test (or not covered).

- [x] Coverage not found for Neo.SmartContract.Testing.Contract_ABIAttributes2
- [x] Coverage not found for Neo.SmartContract.Testing.Contract_ABIAttributes3
- [x] Coverage not found for Neo.SmartContract.Testing.Contract_Event
- [x]  Coverage not found for Neo.SmartContract.Testing.Contract_MultipleA
- [x]  Coverage not found for Neo.SmartContract.Testing.Contract_MultipleB
- [x]  Coverage not found for Neo.SmartContract.Testing.Contract_OnDeployment1
- [x]  Coverage not found for Neo.SmartContract.Testing.Contract_OnDeployment2
- [x]  Coverage not found for Neo.SmartContract.Testing.Contract_PostfixUnary
- [x]  Coverage not found for Neo.SmartContract.Testing.Contract_NEP17
- [x]  Coverage not found for Neo.SmartContract.Testing.Contract_Throw
- [x]  Coverage not found for Neo.SmartContract.Testing.Contract_String
- [x]  Coverage not found for Neo.SmartContract.Testing.Contract_IndexOrRange
- [x]  Coverage not found for Neo.SmartContract.Testing.Contract_Logical
- [x]  Coverage not found for Neo.SmartContract.Testing.Contract_MemberAccess
- [x]  Coverage not found for Neo.SmartContract.Testing.Contract_NEP11

**Comment by Jim8y** [comment]
@shargon need this, please start working on them,
