### ISSUE TITLE
Cryptography does not exist in the namespace 

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-devpack-dotnet#1090]
Compiling with current master I found.
../Contract1.cs(3,11): error CS0234: The type or namespace name 'Cryptography' does not exist in the namespace `

What did change in this namespace?

**Comment by vncoelho** [comment]
I will double check and update dependencies here

**Comment by Jim8y** [comment]
> Are these uses in `TestingArtififacts` and SmartContract.Testing acceptable? https://github.com/search?q=repo%3Aneo-project%2Fneo-devpack-dotnet%20Cryptography.ECC&type=code

No, its just for testing, and is not a real contract.
