### ISSUE TITLE
Add Support for DEBUG

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-devpack-dotnet#1161]
If compiled as `Debug` than it should generate everything inside when `DEBUG` is defined.

```csharp
  public static void TestDebug()
  {
#if DEBUG
    Runtime.Log("Hello, World"); // Isn't generated when target is `Release`
#endif
  }
```

**Comment by shargon** [comment]
Only debug or compiler directives?

**Comment by cschuchardt88** [comment]
> Only debug or compiler directives?

`DEBUG` would be the simplest to start with.

**Comment by shargon** [comment]
I thought that this worked ..
