### ISSUE TITLE
[TestEngine] It doesn't create the new artifacts

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-devpack-dotnet#1180]
While updating the TestCleanUp something we miss, when I create a new contract, the artifacts is not created because you need the test for it, and for create the test for it, you need the artifacts.

How to test:

- Create a contract in test folder.
- Execute the tests.
- No artifacts was created.

**Comment by Jim8y** [comment]
the test depends on the artifacts, therefore we have to create an artifact first, then we can run the test.

**Comment by shargon** [comment]
But if you create a new contract, how do you do?

**Comment by Jim8y** [comment]
> But if you create a new contract, how do you do?

I copy an existing artifact and rename it to the new contract. Then use it to create a new empty unit test class that load the artifact,,,,, when we run the unit test class, it will update the artifact automatically. This can also be done with script, we can add a script.

**Comment by shargon** [comment]
> > But if you create a new contract, how do you do?
> 
> I copy an existing artifact and rename it to the new contract. Then use it to create a new empty unit test class that load the artifact,,,,, when we run the unit test class, it will update the artifact automatically. This can also be done with script, we can add a script.

Ok, we can do this
