### ISSUE TITLE
The implementation of  `MethodConvert.HandleStringTrim` in `SystemCall.String.cs`  has different semantics with C# stdlib

### ISSUE THREAD

**Issue by nan01ab** [neo-project/neo-devpack-dotnet#1186]
`string.Trim()` is used to remove `whitespace` characters before and after a string.

https://github.com/neo-project/neo-devpack-dotnet/blob/add21354263b658f46c66b4738d0296c08fb3b7d/src/Neo.Compiler.CSharp/MethodConvert/System/SystemCall.String.cs#L298

The definition of `whitespace` character in C#, contains more than just space character(i.e. `' '`),  but also other characters(for example: `\t`, `\n`, detail: https://learn.microsoft.com/zh-cn/dotnet/api/system.string.trim?view=net-8.0).

But `MethodConvert.HandleStringTrim` just remove the space character(i.e. `' '`).

In fact,  the `trim`(or other names) method does not just remove space character(`' '`) in common programming languages.

**Comment by Jim8y** [comment]
will fix it.
