### ISSUE TITLE
The `HandleCharIsWhiteSpace` method determines more ASCII characters as whitespace than the C# `char.IsWhiteSpace`

### ISSUE THREAD

**Issue by nan01ab** [neo-project/neo-devpack-dotnet#1188]
`char.IsWhiteSpace` is used to determine a `char` that is whitespace character or not.
The implementation of `HandleCharIsWhiteSpace` in
https://github.com/neo-project/neo-devpack-dotnet/blob/add21354263b658f46c66b4738d0296c08fb3b7d/src/Neo.Compiler.CSharp/MethodConvert/System/SystemCall.Char.cs#L80
determines  all characters in `[9, 14)` and `[10, 33)` as whitespace character.

But in C# `char.IsWhiteSpace`, only determines characters in `[9, 14)`  and `32` as whitespace character:
```csharp
    static class Program 
    {
        static void Main(string[] args)
        {
            for (int i = 0; i < 128; i++)
            {
                char c = (char)i;
                Console.WriteLine($"IsWhiteSpace: {i}: {char.IsWhiteSpace(c)}");
            }
        }
    }
```

**Comment by shargon** [comment]
https://github.com/Microsoft/referencesource/blob/master/mscorlib%2Fsystem%2Fchar.cs#L272

**Comment by nan01ab** [comment]
> https://github.com/Microsoft/referencesource/blob/master/mscorlib%2Fsystem%2Fchar.cs#L272

https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/mscorlib/system/char.cs#L248

`(c == ' ') || (c >= '\x0009' && c <= '\x000d')` for ASCII characters
```csharp
       private static bool IsWhiteSpaceLatin1(char c) {

            // There are characters which belong to UnicodeCategory.Control but are considered as white spaces.
            // We use code point comparisons for these characters here as a temporary fix.
        
            // U+0009 = <control> HORIZONTAL TAB
            // U+000a = <control> LINE FEED
            // U+000b = <control> VERTICAL TAB
            // U+000c = <contorl> FORM FEED
            // U+000d = <control> CARRIAGE RETURN
            // U+0085 = <control> NEXT LINE
            // U+00a0 = NO-BREAK SPACE
            if ((c == ' ') || (c >= '\x0009' && c <= '\x000d') || c == '\x00a0' || c == '\x0085') {
                return (true);
            }
            return (false);
        }
}
```
