### ISSUE TITLE
Mint multiple NEP11 tokens causes Peek out of bounds: 0/0

### ISSUE THREAD

**Issue by GreenCakes-png** [neo-project/neo-devpack-dotnet#1224]
Copied this example "[examples/Example.SmartContract.SampleRoyaltyNEP11Token](https://github.com/neo-project/neo-devpack-dotnet/tree/master/examples/Example.SmartContract.SampleRoyaltyNEP11Token)"

I added a method to mint multiple tokens at once like this:

public static void MultiMint(UInt160 to)
{
    Mint(to);
    Mint(to);
    Mint(to);
    Mint(to);
}

However when I call this method, the NEO CLI throws "Peak out of bounds..." error

![image](https://github.com/user-attachments/assets/aed21a16-41dd-4aeb-b422-1289b85b5659)

Could someone help identify the cause or suggest a solution?
Is it not possible to mint multiple tokens at once?

**Comment by Jim8y** [comment]
I'll take a look

**Comment by Hecate2** [comment]
Could you provide any contract source code, the compiler version, or the .nef, .manifest.json, .nefdbgnfo?
Also you may try neo-fairy-test.

**Comment by Jim8y** [comment]
@shargon can you please check this logic here, the problem is caused by this check:

https://github.com/neo-project/neo-devpack-dotnet/blob/65654df63f60c436f1c8d292975a6bbe831b652d/src/Neo.Compiler.CSharp/MethodConvert/PropertyConvert.cs#L128

if you call a `storebacked` property twice, you will be able to trigger this problem, cause the first call will initialize the property and make it none null, then the second call to the property will jump all the way to the bottom of the `get` method.

**Comment by Jim8y** [comment]
simply do this will reproduce the issue. 

```C#
        public static void MultiMint(UInt160 to)
        {
            TotalSupply++;
            TotalSupply++;
        }
```

**Comment by shargon** [comment]
> @shargon can you please check this logic here, the problem is caused by this check:
> 
> https://github.com/neo-project/neo-devpack-dotnet/blob/65654df63f60c436f1c8d292975a6bbe831b652d/src/Neo.Compiler.CSharp/MethodConvert/PropertyConvert.cs#L133
> 
> if you call a `storebacked` property twice, you will be able to trigger this problem, cause the first call will initialize the property and make it none null, then the second call to the property will jump all the way to the bottom of the `get` method.

this is supposed to be the instance, and because is static, should be null :S

**Comment by Hecate2** [comment]
```
CurrentScriptHash=0x01f31fb35734aa143f1274da79129acf97309561[SampleRoyaltyNEP11Token]
EntryScriptHash=0x1f4435477ad4edeb6affd95bff88714f3ec66809
   at Neo.VM.ExecutionEngine.ExecuteNext() in C:\Users\RhantolkYtriHistoria\NEO\neo-node-mainnet\src\Neo.VM\ExecutionEngine.cs:line 148
	InstructionPointer=63, OpCode , Script Length=63 0x1f4435477ad4edeb6affd95bff88714f3ec66809[]
File test-compiler.cs, line 43: to
	InstructionPointer=937, OpCode LDARG0, Script Length=1929 0x01f31fb35734aa143f1274da79129acf97309561[SampleRoyaltyNEP11Token]
File test-compiler.cs, line 122: }
	InstructionPointer=1030, OpCode RET, Script Length=1929 0x01f31fb35734aa143f1274da79129acf97309561[SampleRoyaltyNEP11Token]
File Nep11Token.cs, line 116: TotalSupply++
	InstructionPointer=908, OpCode DUP, Script Length=1929 0x01f31fb35734aa143f1274da79129acf97309561[SampleRoyaltyNEP11Token]
   at Neo.VM.ExecutionEngine.ExecuteNext() in C:\Users\RhantolkYtriHistoria\NEO\neo-node-mainnet\src\Neo.VM\ExecutionEngine.cs:line 148
Peek out of bounds: 0/0
```
[SampleRoyaltyNEP11Token.nef.txt](https://github.com/user-attachments/files/17655053/SampleRoyaltyNEP11Token.nef.txt)

**Comment by Hecate2** [comment]
A bug in the compilation of `Neo.SmartContract.Framework.TokenContract.TotalSupply.get`
```python
# Method Start Neo.SmartContract.Framework.TokenContract.TotalSupply.get
# Code TokenContract.cs line 28: "[Safe] get;"
0018 LDSFLD0
# Code TokenContract.cs line 28: "[Safe] get;"
0019 ISNULL
# Code TokenContract.cs line 28: "[Safe] get;"
0020 JMPIFNOT 17 # pos: 43 (offset: 23)
...
# Method End Neo.SmartContract.Framework.TokenContract.TotalSupply.get
# Code TokenContract.cs line 28: "[Safe] get;"
0043 RET
```
Value of static field 0 is not returned.
