### ISSUE TITLE
Banning the use of non-static fields, properties, and methods.

### ISSUE THREAD

**Issue by Jim8y** [neo-project/neo-devpack-dotnet#1239]
The use of non-static fields and properties are wrong, and can not be fixed in an easy way, the reason of the problem is that static field/property can be initialized in a static constructor, while non-static have to be initialized when an object is created, yet no instance will be created for smartcontract. Thus all non-static field/properties can not be initizalied properly. A solution of this would be inserting opcode to initialize those fields when loading the conrtact, but that will just be the same as banning the use of non-static fields/property, and it makes more sense for me since contract will not have any instance anyway (interoperation and reentry will be consisdered totally different environment, static field/property will not be shared.). 

And to align with the banning of using non-static field/property, we can also ban the use of non-static methods, to make the experience unified.

**Comment by Jim8y** [comment]
```C#
        private readonly static UInt160 uInt160 = "NXV7ZhHiyM1aHXwpVsRZC6BwNFP2jghXAq";

        private BigInteger value = 11;

        private  BigInteger TestProperty { get; set; }

        public  BigInteger TestProperty2 { get; set; } = 10;
        
        public static BigInteger TestProperty3
        {
            get => value;
            set { }
        }
```

above are test cases

**Comment by Jim8y** [comment]
Too complex to handle non-static property correctly, too many places need to be updated, and many of them actually did not handle static-non static property/field at all. It is very easy to make mistakes, better to ban defining non-static symbols in smart contract.

**Comment by Jim8y** [comment]
@shargon please consider. I can update analyzer to enforce this.

**Comment by shargon** [comment]
For me is good if we ban until is solved

**Comment by Hecate2** [comment]
I think it has been solved in https://github.com/neo-project/neo-devpack-dotnet/pull/1246
