### ISSUE TITLE
Neo 2 devpack not passing tests

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-devpack-dotnet#126]
**How to reproduce:**
- Clone neo-devpack-dotnet
- Checkout master-2.x
- Open the solution
- Run MSIL Unit tests

Result:
![image](https://user-images.githubusercontent.com/38396062/68246014-c1cd3680-fff6-11e9-9bc8-6820b7cee82d.png)

I managed to fix some tests (the problem was the dll name was misconfigured), but now I have a much bigger concern: the code is actually broken.
This works:

```Csharp
public static string UnitTest_003()
{
       return "Unit Test";
}
```
But this doesn't:

```Csharp
public static byte UnitTest_001()
{
     var nb = new byte[] { 1, 2, 3, 4 };
     return nb[2];
}
```

@devhawk

**Comment by lock9** [comment]
Tests are passing in #127. I don't know, but I think that this was caused by using the code reference. Maybe we have an issue in the latest version of the compiler  or VM?

**Comment by lightszero** [comment]
https://github.com/neo-project/neo-devpack-dotnet/pull/122#issuecomment-549934301

**Comment by lock9** [comment]
Thanks @lightszero
