### ISSUE TITLE
Neon should be able to compile from the source

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-devpack-dotnet#132]
For developers we have two steps in order to compile from a c# code.
- First we need to compile the c# into .net assembly.
- Then compile it in neon.

I want to allow neon to do all in one step.

Proposed solution: https://github.com/neo-project/neo-devpack-dotnet/pull/131

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-devpack-dotnet/blob/a75cad579e00a1429ead5f9103917b6922791d5b/tests/Neo.Compiler.MSIL.UnitTests/Utils/NeonTestTool.cs#L49

With these codes, I think it is possible.

**Comment by shargon** [comment]
Yes, I copied this code into https://github.com/neo-project/neo-devpack-dotnet/pull/131

**Comment by lightszero** [comment]
I think we need add a build function from .csproj.
build from single cs file is useful too.
we can keep them both.

**Comment by shargon** [comment]
I will add this feature too

**Comment by shargon** [comment]
Any package for reading the `csproj`?

**Comment by lightszero** [comment]
i have a project to do that，i will find it tomorow

**Comment by lightszero** [comment]
https://github.com/lightszero/sharp2typescript/blob/master/CodeConverter/Convert.cs

see AddProject
it use Buildalyzer for read csproj and support for rosyln.
