### ISSUE TITLE
Need to remove conditional compilation

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo-devpack-dotnet#143]
https://github.com/neo-project/neo-devpack-dotnet/blob/63e90e567b50c41d1f4e1d621830ebc4020cbf9f/src/Neo.Compiler.MSIL/MSIL/Converter.cs#L46

https://github.com/neo-project/neo-devpack-dotnet/blob/63e90e567b50c41d1f4e1d621830ebc4020cbf9f/src/Neo.Compiler.MSIL/MSIL/Converter.cs#L1145

https://github.com/neo-project/neo-devpack-dotnet/blob/63e90e567b50c41d1f4e1d621830ebc4020cbf9f/src/Neo.Compiler.MSIL/MSIL/ILModule.cs#L23

We should remove these conditional compilations.

**Comment by lock9** [comment]
@erikzhang  do you think we should remove  #if NET47 from all projects? Is it done already? I don't remember if we removed .net framework 4.7 completely or not.

**Comment by erikzhang** [comment]
I'm sure we have no NET47 any more. The last .NET Framework project is neo-gui, which has been ported to .NET Core 3.0.

**Comment by devhawk** [comment]
Even if neo-gui was still on .NET Framework, that shouldn't block NEON from targeting .NET core only
