### ISSUE TITLE
Include contract metadata in .abi.json file (master-2.x branch)

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#144]
I propose including contract deployment information in the .abi.json file generated by NEON compiler. NEON could retrieve this information from assembly attributes specified in the C# source code (and provide reasonable defaults if the values are not specified). 

By declaring this information in source, we reduce the information needed at deployment time, making it easier to automate deployment via neo-express and/or visual devtracker

NEON would generate contract metadata as follows:

* title would come from file name
* description would come from [AssemblyDescriptionAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblydescriptionattribute)
* version would come from [AssemblyVersionAttribute ](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblyversionattribute)
* author and email would come from [AssemblyMetadataAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblymetadataattribute)
* hasStorage, hasDynamicInvoke, isPayable properties would from newly defined attributes that we add to [Neo.SmartContract.Framework](https://github.com/neo-project/neo-devpack-dotnet/tree/master-2.x/Neo.SmartContract.Framework)

**Comment by lock9** [comment]
I think this is a good idea.
@neo-project/core  can @devhawk  continue to implement this?

**Comment by shargon** [comment]
I like it

**Comment by devhawk** [comment]
I will work on an implementation then.

**Comment by erikzhang** [comment]
Please, don't change 2.x any more. We need to focus more on 3.0.

**Comment by shargon** [comment]
This could be implemented in neo3

**Comment by devhawk** [comment]
@erikzhang developer tools are currently blocked waiting on a preview release of neo 3 that support contract deployment. In the meantime, I need to continue to make progress on Neo 2 developer tools.

@shargon Neo 3 doesn't need this - the new manifest serves a similar purpose.

**Comment by devhawk** [comment]
I filed #151 to track porting whatever parts of this work are needed by Neo3

**Comment by devhawk** [comment]
FYI, my understanding is that NEON for neo 3 generates a manifest that contains this contract metadata. If we would rather have someone from @neo-project/core backport manifests to Neo 2, I'm fine with that approach as well.
