### ISSUE TITLE
Generate Debug Info needed for neo-debugger in NEON (3.x branch)

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#150]
This is the 3.x version of #149. FYI, this work will start in the Neo3 preview timeframe

**Comment by lightszero** [comment]
we can't make the debug info standard quilkly.
how about we add a plugin interface for neon.so can add debuginfo plugin for neon.
what do you think?

**Comment by devhawk** [comment]
I'm fine with that, though it doesn't seem worth it. I tried reaching out to several of the other language implementations (neo-one and neo-python in particular) and got zero feedback. Unless there are changes to the format needed for neo3 support, it seems simpler to just add that to neon directly.

**Comment by devhawk** [comment]
This was fixed by #298
