### ISSUE TITLE
Create NEP-5 template for Neo3

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-devpack-dotnet#152]
NEP-5
- [x] Mint tokens based in GAS / Token input
- [x] Transfer tokens to smart contract
- [ ]  Transfer funds from smart contract (verification trigger)
- [ ]  Create new NEP-5 template (reference code)

From Native NEP-5
- [x]  Allow contract to accept Native Gas
- [x]  Allow contract to accept Native Neo 
- [ ] Transfer funds to smart contract using MultiSig
- [ ] Withdraw funds from smart contract using MultiSig

From Neo-cli
- [x]  Neo-cli: Allow NEP-5 contract to be deployed and called

Note: This is not an 'ICO' template, only NEP-5 (for now)

**Comment by Tommo-L** [comment]
@shargon Could help close this issue, sine #187 has already been merged.
