### ISSUE TITLE
Use a Command Line Processing Library for NEON (master + master 2.x)

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#153]
As NEON evolves, it would be useful for it to support more command line options. Instead of manually processing these options, we should use a library. 

Possible library suggestions:
* [natemcmaster/CommandLineUtils](https://github.com/natemcmaster/CommandLineUtils) - a mature command line processing library originally forked from now-defunct  Microsoft.Extensions.CommandLineUtils project. Neo-Express uses this library.
* [dotnet/command-line-api](https://github.com/dotnet/command-line-api) a new (and still immature) command line processing library that appears to be slated to become the official command line processing solution from Microsoft for .NET

**Comment by devhawk** [comment]
IMO, dotnet/command-line-api has a ton of promise but is simply to early in it's development. I suggest we use natemcmaster/CommandLineUtils.

**Comment by shargon** [comment]
I tried in the past, but we only receive one parameter and was removed https://github.com/neo-project/neo-devpack-dotnet/commit/821304c2fd82f53bb48985a43ff1e8a6a01e576f#diff-60ea751d2c3b42b8832fdf636c718f42R7

**Comment by devhawk** [comment]
I would like to add parameters that control debug info output. And master-2.x branch has the one parameter (note, this issue is listed as affecting master 2.x and master branches)
