### ISSUE TITLE
Unify master-2.x contract metadata attributes with master branch

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#158]
Master branch has added `FeatureAttribute` while master-2.x has ContractHasStorage/ContractHasDynamicInvoke/ContractIsPayable. Need to change master-2.x to match master branch

**Comment by devhawk** [comment]
@shargon I'd appreciate your thoughts on this issue. I started to do this, but I ran into a few incompatibilities:

* FeaturesAttribute is applied to a class while all of the contract attributes I added are applied to the assembly. As far as I understand, NEON doesn't support multiple contracts in a single managed dll - at least for 2.x. If that's the same for NEON 3.x, should FeaturesAttribute be applied to the assembly not the class? Or should all the 2.x attributes apply to class instead of assembly. 
  * My preference is to attach these attributes to assembly not class. What does it mean to attach these attributes to classes *other* than the main contract class?
* FeaturesAttribute uses the ContractFeatures enum, but the 2.x branch already has the ContractPropertyState enum. I don't think we should define to enums with the same values and we can't change the existing ContractPropertyState enum without breaking code. I'm thinking the 2.x branch version of FeaturesAttribute should just take a ContractPropertyState value in its constructor, even though it's not 100% compatible with 3.x branch.

**Comment by shargon** [comment]
> should FeaturesAttribute be applied to the assembly not the class?

Yes, I think so.

> even though it's not 100% compatible with 3.x branch.

Don't worry about that, it's ok for me

**Comment by shargon** [comment]
Seems weird to me with smart contracts with one file.

```csharp
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;

[assembly: Features(ContractFeatures.HasStorage)]

namespace Neo.Compiler.MSIL.TestClasses
{
    class Contract_Storage : SmartContract.Framework.SmartContract
    {
```

**Comment by shargon** [comment]
Please @devhawk , Take a look to https://github.com/neo-project/neo-devpack-dotnet/pull/161

**Comment by devhawk** [comment]
Not all contracts are a single file: https://github.com/Moonlight-io/moonlight-ico-template
What would it mean for you to apply the features attribute to the [NEP5 class](https://github.com/Moonlight-io/moonlight-ico-template/blob/master/ICOTemplate/Token/NEP5.cs) but not the [main entrypoint class](https://github.com/Moonlight-io/moonlight-ico-template/blob/master/ICOTemplate/ICOTemplate.cs)?

**Comment by devhawk** [comment]
@shargon I like #161. Note also that I have a [task open](https://github.com/ngdseattle/neo-templates/issues/1) to add these attributes for the neo contract templates. So developers starting from scratch will know how to add them.

**Comment by devhawk** [comment]
@shargon I have https://github.com/devhawk/neo-devpack-dotnet/tree/devhawk/FeaturesAttribute ready to go, but I will wait on submitting that for PR until this one goes thru.
