### ISSUE TITLE
Debug neon in master2x

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-devpack-dotnet#173]
@devhawk I was not able to debug neon in master 2x after merge https://github.com/neo-project/neo-devpack-dotnet/pull/166 , maybe we need to define 

`<TargetFramework>netcoreapp3.1</TargetFramework>` as default in the csproj.

I need to do these changes if I want to debug it

![image](https://user-images.githubusercontent.com/3167973/71030960-bd765c00-2112-11ea-92b7-3626e1954553.png)

**Comment by devhawk** [comment]
I'll take a look
