### ISSUE TITLE
Add StorageIterator

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-devpack-dotnet#19]
It's added to `neo-project` but not yet in the smart contract framework so can't use it.
https://github.com/neo-project/neo/commit/a234978f2

**Comment by ixje** [comment]
Note that I've been able to compile a contract with `Storage.Find` using [this fork](https://github.com/neo-project/neo-devpack-dotnet/compare/master...ConjurTech:add-apis) however there seem to be 2 issues

1) The iterator cannot be used in a `foreach` loop due to a missing public definition of `GetEnumerator`
![img](https://imgur.com/gmBbNXA.png)

2) prefix searching doesn't seem to work, returns an empty 'list' given the code below and only prints
>Starting
> Done
```csharp
    public class Contract1 : SmartContract
    {
        public static void Main()
        {
            Storage.Put(Storage.CurrentContext, "my_prefixA", "1");
            Storage.Put(Storage.CurrentContext, "my_prefixB", "2");
            Storage.Put(Storage.CurrentContext, "something", "3");
            StorageIterator si = Storage.Find(Storage.CurrentContext, "my_prefix");

            Runtime.Notify("Starting");
            while (si.Next())
            {
                Runtime.Notify(si.Key);
            }
            Runtime.Notify("Done");
        }
    }
```

**Comment by RavenXce** [comment]
Yes, I believe the implementation of StorageIterator is bugged. I've been meaning to file a separate issue. I think the key prefix should have a length between it and the scriptHash.

**Comment by ixje** [comment]
Thanks for the quick handling of the bug in https://github.com/neo-project/neo/pull/200 🥇! Looking forward to see this issue resolved so I can finalise the `neo-python` implementation with some cross platform tests

**Comment by ixje** [comment]
hi @erikzhang, you closed this issue but it's actually not resolved yet. Only the neo core `Storage.Find` implementation is fixed, but this official devpack does not support `Storage.Find` yet so others cannot use it unless they know about and use the fork from @RavenXce / Switcheo https://github.com/neo-project/neo-devpack-dotnet/compare/master...ConjurTech:add-apis

**Comment by RavenXce** [comment]
I will make a PR since it works correctly now.
