### ISSUE TITLE
split Neon.compiler.MSIL to 2 project

### ISSUE THREAD

**Issue by lightszero** [neo-project/neo-devpack-dotnet#190]
Neo.compiler.MSIL -> dll
Neo.compiler.MSIL.CIL -> exe

what do you think?

**Comment by shargon** [comment]
As compilers (executable) or libreries? `Neon` or `Neo`?

**Comment by lightszero** [comment]
cil project depends on dll project。
Neo

**Comment by lightszero** [comment]
what do you think.

split the code

Neo.compiler.MSIL.dll ( net standard)

Neo.compiler.MSIL.CLI.exe(net core)

@shargon @Tommo-L

**Comment by Tommo-L** [comment]
For me, it's ok.  If both are sub-projects of `neo-devpack-dotnet`.

**Comment by erikzhang** [comment]
Why?

**Comment by lightszero** [comment]
some project need compiler service.
after split,they can just reference the dll  without hack
like nuget install Neo.compiler.MSIL.dll ( net standard).

**Comment by erikzhang** [comment]
But exe can be referenced too.

**Comment by lightszero** [comment]
> But exe can be referenced too.

   good point...ORZ
