### ISSUE TITLE
AsByteArray() isn't able to convert BigInteger to ByteArray

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-devpack-dotnet#195]
When I test nep5 sc, I'd like to put 0 into account storage when balanceOf return null, so I write as below:
```
        [DisplayName("BalanceOf")]
        public static BigInteger BalanceOf(byte[] account)
        {
            if (account.Length != 20)
                throw new InvalidOperationException("The parameter account SHOULD be 20-byte addresses");
            var balance = Storage.Get(Storage.CurrentContext, account);
            BigInteger zero = 0;
            byte[] byteZero = zero.AsByteArray();
            if (balance is null)
            {
                Storage.Put(Storage.CurrentContext, account, byteZero);
            }
            return Storage.Get(Storage.CurrentContext, account).AsBigInteger();
        }
```
Then I found this `byteZero` is not a byteArray but still return BigInteger 0 which cause RPC getBalance return 0 if one of addresses in a wallet doesn't have balance.
Then I tried another style, it works well.  This means `AsByteArray()` here isn't work normally.
![image](https://user-images.githubusercontent.com/38493437/75870376-da831700-5e45-11ea-9018-f4c8db2e8683.png)
Then I found `AsByteArray()` isn't able to conver BigInteger to ByteArray but just transfer it to VM. This makes me a little confused. Since native C# conversion method `ToByteArray()` isn't able to be used in sc.framework, we don't have a method support `BigInteger` to `ByteArray` on sc framework.
@erikzhang @lightszero @shargon

**Comment by Tommo-L** [comment]
Currently, the `AsByteArray` is an empty script.
https://github.com/neo-project/neo-devpack-dotnet/blob/adf942550c5dd2defa8440038f8a2daad145d630/src/Neo.SmartContract.Framework/Helper.cs#L50-L55

I think there are two options:
option1: Add a new opcode `Cast` for converting.
option2: Add a new method `AsByteArray` in `StackItem`.

**Comment by shargon** [comment]
we have the CONVERT opcode, we can use it

**Comment by lightszero** [comment]
'CONVERT', that's new for me.sounds it fit this issue.

**Comment by lightszero** [comment]
I had create a unittest, it worked.
```c#
    class Contract_TypeConvert : SmartContract.Framework.SmartContract
    {
        //Integer = 0x21,
        //ByteArray = 0x28,
        [OpCode(SmartContract.Framework.OpCode.CONVERT, "0x28")]
        public extern static byte[] ConvertToByteArray(object from);


        [OpCode(SmartContract.Framework.OpCode.CONVERT, "0x21")]
        public extern static BigInteger ConvertToInteger(byte[] from);




        public static object testType()
        {
            BigInteger int0 = 0;
            var bts0 = ConvertToByteArray(int0);
            BigInteger int1 = 2;
            var bts1 = ConvertToByteArray(int1);

            var bts2=new byte[1] { 3 };
            var int2 = ConvertToInteger(bts2);

            var bts3 = ConvertToByteArray(new byte[0]) ;
            var int3 = ConvertToInteger(bts3);

            var arrobj = new object[8];
            arrobj[0] = int0;
            arrobj[1] = bts0;
            arrobj[2] = int1;
            arrobj[3] = bts1;
            arrobj[4] = bts2;
            arrobj[5] = int2;
            arrobj[6] = bts3;
            arrobj[7] = int3;
            return arrobj;
        }


    }
```
