### ISSUE TITLE
Add UInt160 and UInt256 data types

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-devpack-dotnet#208]
**Summary or problem description**

As UInt160, UInt256 are one of the most commonly used data types, I think we should abstract them  into basic types. Here is a [switcheo contract](https://github.com/Switcheo/switcheo-neo/blob/58bbb947d41f0bbec9563231b9f90f39f0f7bfbf/switcheo/BrokerContract.cs), as you can see, scripthash(UInt160) are widely used.

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- VM
- Neo
- Compiler

**Comment by lightszero** [comment]
yes，why not add a stacktype UInt160？

**Comment by shargon** [comment]
I think that it could be done in neo-dev-pack, and leave the vm to be non neo-dependant

**Comment by igormcoelho** [comment]
UInt160 and UInt256 are nothing more than ByteArray with Length check (== 20, or ==32).
In my opinion (I need to see precisely what's being done there), it would be nice to have some OBJECTS on devpack, where devpack compiler automatically adds these "type checks" on every function call. This would add extra security for programmers, although I think that basic assertions such as "size == 20" should continue to be done, as a good practice, besides the efforts of compilers. This is also good for other communities, like python and go, to make sure their compilers also have these checks.
