### ISSUE TITLE
Sync new opcode: ASSERT,  ABORT

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-devpack-dotnet#209]
waiting for https://github.com/neo-project/neo-vm/pull/300

**Comment by ProDog** [comment]
I have tested it passed.
Contract:

![image](https://user-images.githubusercontent.com/12728872/77738396-bc769400-704a-11ea-9ca3-7b6ba5aaeeb4.png)

Invoke result:
for assert(true):

![image](https://user-images.githubusercontent.com/12728872/77738475-dd3ee980-704a-11ea-90e3-0922cf739be1.png)
![image](https://user-images.githubusercontent.com/12728872/77738490-e3cd6100-704a-11ea-85bf-94be2664c51b.png)

for assert(false):

![image](https://user-images.githubusercontent.com/12728872/77738603-1aa37700-704b-11ea-9059-0152d79f9f59.png)

for abort:

![image](https://user-images.githubusercontent.com/12728872/77738688-40308080-704b-11ea-8bc1-107dc6a9b639.png)
