### ISSUE TITLE
A contract compile error when Storage.Put byte[]

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-devpack-dotnet#212]
Contract compilations report errors when byte[] length exceeds 16,like this:
![image](https://user-images.githubusercontent.com/12728872/77028508-ed642280-69d3-11ea-862d-cd39045b7077.png)
![image](https://user-images.githubusercontent.com/12728872/77028583-23a1a200-69d4-11ea-8ef6-776a22559008.png)

**Comment by Tommo-L** [comment]
I'll have a try to fix it.

**Comment by shargon** [comment]
Miss click?
