### ISSUE TITLE
Contract compile issues for Helper.HexToBytes and Helper.ToScriptHash

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-devpack-dotnet#213]
A contract compiler error for Helper.HexToBytes() and Helper.ToScriptHash():

![image](https://user-images.githubusercontent.com/12728872/77029220-0ec60e00-69d6-11ea-9f9c-8fcfc7c60bff.png)
![image](https://user-images.githubusercontent.com/12728872/77029277-374e0800-69d6-11ea-9b49-e00f045a3155.png)

**Comment by shargon** [comment]
Currently it only works with static variables

https://github.com/neo-project/neo-devpack-dotnet/blob/b51c2b1afef9ad1fcfc2f0626e2e0f4ea26465bd/src/Neo.Compiler.MSIL/MSIL/Conv_Multi.cs#L219

**Comment by ProDog** [comment]
OK

**Comment by Tommo-L** [comment]
@ProDog plz keep it open, we may need to fix it in the future.
