### ISSUE TITLE
Contract compile issues for Helper.Reverse()

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-devpack-dotnet#217]
A contract compiler error for Helper.Reverse(this byte[] source),like:
![image](https://user-images.githubusercontent.com/12728872/77382176-a783d180-6dba-11ea-85c9-ed5292b21db6.png)

**Comment by ProDog** [comment]
When contract included code like var a = 12.AsSbyte(); it will throw exceptions when deploy contract:

![image](https://user-images.githubusercontent.com/12728872/77383017-d69b4280-6dbc-11ea-8a50-aa34fb245a7e.png)

Same exceptions:
```
.AsByte() => OpCode:241 => System.FormatException: 'OpCode not found at 1804-f1'
.ToByte() => OpCode:57 => System.FormatException: 'OpCode not found at 3379-39'
.ToSbyte() => OpCode:57 => System.FormatException: 'OpCode not found at 3403-39'
```

**Comment by ShawnYun** [comment]
The problem of the `Helper.Reverse()` seems to be that this instruction `CodeEx.Stelem_I1` is not supported now.
![ste](https://user-images.githubusercontent.com/42930111/77719219-b919e300-701f-11ea-8404-82001551c0e9.PNG)
@lightszero Can we solve this problem now？

**Comment by Tommo-L** [comment]
I think we can solve it now, as we have `Opcode.REVERSEITEMS`. I'll help fix it.
