### ISSUE TITLE
Contract invoke exceptions for byte[] Concat:

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-devpack-dotnet#218]
When contract included code:
```
return (new byte[] { 0x12, 0x23, 0x32 }).Concat(new byte[] { 0x55, 0x23 });
```
or
```
Runtime.Notify((new byte[] { 0x12, 0x23, 0x32 }).Concat(new byte[] { 0x55, 0x23 }));
```
it will throw exceptions when invoke contract:

![image](https://user-images.githubusercontent.com/12728872/77391418-a7dc9680-6dd3-11ea-95b5-c20de28023f6.png)

**Comment by ProDog** [comment]
.Range(), .Take(), .Last() have the same exception:
Contract included code:
```
return (new byte[] { 0x12, 0x23, 0x32 }).Range(0, 1); 
Runtime.Notify((new byte[] { 0x12, 0x23, 0x32 }).Range(0, 1));
return (new byte[] { 0x12, 0x23, 0x32 }).Take(1);
Runtime.Notify((new byte[] { 0x12, 0x23, 0x32 }).Take(1));
return (new byte[] { 0x12, 0x23, 0x32 }).Last(1);
Runtime.Notify((new byte[] { 0x12, 0x23, 0x32 }).Last(1));
```
Throw exceptions when invoke contract:

![image](https://user-images.githubusercontent.com/12728872/77394488-7ddaa280-6dda-11ea-88aa-a80224b95b4b.png)

**Comment by erikzhang** [comment]
I think we should add a new type `ByteArray` in devpack. We should not return `byte[]` directly.

**Comment by Tommo-L** [comment]
I'll help fix this issue.

**Comment by ProDog** [comment]
This exception occurs: 
- using `ApplicationLog` plugin, contract including `Runtime.Notify(byte[])`;
- return result to neo-cli, contract including `return byte[]`.

**Comment by Tommo-L** [comment]
Got, @bettybao1209  is alrady working on it.
