### ISSUE TITLE
Initialize the static variables without main method.

### ISSUE THREAD

**Issue by ShawnYun** [neo-project/neo-devpack-dotnet#237]
As #219 , we add abi offset for every method. But if there are static variables, we need to load them first.

**Comment by erikzhang** [comment]
@lightszero What do you think?

**Comment by shargon** [comment]
We should call the static constructor first

**Comment by Tommo-L** [comment]
Maybe we need a constructor method for each contract, like c# class?

**Comment by lightszero** [comment]
简洁的修改方式 是 懒汉模式，在每个入口函数插入一个检查。

**Comment by shargon** [comment]
But it should be executed once, if we call a recursive method, we should be executed only once.

```
Exec(int a, int b, int counter)
{
 // STATIC INIT
 if (counter>10)return a+b;
 return Exec(a+b,b+1,counter+1);
}
```

**Comment by Tommo-L** [comment]
> 简洁的修改方式 是 懒汉模式，在每个入口函数插入一个检查。

Translate to EN:

A simple way is to use lazy mode, insert a check method to init those static variables at the entry of each function.

**Comment by Tommo-L** [comment]
> But it should be executed once, if we call a recursive method, we should be executed only once.

If we use lazy mode, it's not a problem.

**Comment by Tommo-L** [comment]
@erikzhang If we want to use lazy mode, could we add a new opcode `SFCOUNT`, which return the total amount of static field slot. Then we can use it to determine whether static variables have been loaded.

```cs
if static field slot is null return null
else return slot.count
```

**Comment by Tommo-L** [comment]
Another way is that when we deploy a contract at the begining, we should call its constructor to complete its initialization(including static variables)

**Comment by erikzhang** [comment]
My solution is that we allow the contract to have an optional special method: `_initsslot()`.

When an contract is invoked, we check its ABI first. If it has the method `_initsslot()`, we call it first.

**Comment by shargon** [comment]
we can call it in other execution context, and after it, call the user method

**Comment by Tommo-L** [comment]
> allow the contract to have an optional special method: _initsslot().

Personally, I don't want to see that we have too many special functions, we already have one. I think we can adjust NEF format, make NEF like window's exe format, which have different segments.

**Comment by Tommo-L** [comment]
I think we can implement the `__initsslot` now. I have read the [windows PE format](https://docs.microsoft.com/en-us/previous-versions/ms809762(v=msdn.10)?redirectedfrom=MSDN#pe-file-exports), it has a function address table and function name table for mapping. By using `.ctor` as object instance entry,  `.cctor` as class static methods and variables initialization. It also has a `.data` sgement, but it's for user-define. 

![image](https://user-images.githubusercontent.com/43396869/79297194-0814b300-7f10-11ea-8927-ff4441622000.png)

**Comment by shargon** [comment]
It's a good idea, if we process the static constructor, and after it, we save the static variables in the nef file, it could be easier to execute.

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/pull/1572

**Comment by lightszero** [comment]
got it

**Comment by ShawnYun** [comment]
close it via #219 .
