### ISSUE TITLE
OpCode exceptions when deploy contract

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-devpack-dotnet#241]
When contract included code like var a = 12.AsSbyte(); it will throw exceptions when deploy contract:

![image](https://user-images.githubusercontent.com/12728872/77383017-d69b4280-6dbc-11ea-8a50-aa34fb245a7e.png)

Same exceptions:
```
.AsByte() => OpCode:241 => System.FormatException: 'OpCode not found at 1804-f1'
.ToByte() => OpCode:57 => System.FormatException: 'OpCode not found at 3379-39'
.ToSbyte() => OpCode:57 => System.FormatException: 'OpCode not found at 3403-39'
```

_Originally posted by @ProDog in https://github.com/neo-project/neo-devpack-dotnet/issues/217#issuecomment-602983780_

**Comment by shargon** [comment]
`neo-node` has updated the opcodes?

**Comment by ProDog** [comment]
> `neo-node` has updated the opcodes?

no. it's not fixed in  https://github.com/neo-project/neo-devpack-dotnet/issues/217

**Comment by Tommo-L** [comment]
We need to fix this issue, as we have removed `THROWIFNOT` opcode, which replaced by `ASSERT(0x38)`.

https://github.com/neo-project/neo-devpack-dotnet/blob/8a8b1beff6e01645250e065399d1ac061187ac8f/src/Neo.SmartContract.Framework/Helper.cs#L62-L108

**Comment by shargon** [comment]
I will fix it and remove all the hardcode values
