### ISSUE TITLE
Allow multiple return in abi.json

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-devpack-dotnet#243]
For https://github.com/neo-project/neo-devpack-dotnet/pull/238, we have allowed multiple return in contract, so how to show `returnType`  in abi.json and mainfest.json? it's need to support in `Compiler`.

**Comment by lightszero** [comment]
ProDog:
```
 {
            "name":"return",
            "parameters":
            [
                {
                    "name":"a",
                    "type":"Integer"
                },
                {
                    "name":"b",
                    "type":"Integer"
                }
            ],            
            "returnType":["Integer","Integer"]
}
```

Erik:"We shouldn't support multiple return in public methods."

@devhawk @shargon  @Tommo-L what do you think?

**Comment by lightszero** [comment]
this is about https://github.com/neo-project/neo-debugger/issues/17
too.

**Comment by Tommo-L** [comment]
Some solutions:

option A: VM.Array
option B: VM.Struct
Option C: Disallow multipe return

**Comment by Tommo-L** [comment]
I vote for Opion C, it'll be simple for another language, which don't support multipe return.

**Comment by ProDog** [comment]
> I vote for Opion C, it'll be simple for another language, which don't support multipe return.

so we only use it inside the contract?

**Comment by Tommo-L** [comment]
> so we only use it inside the contract?

Yes, it's decided by the compiler.

**Comment by ProDog** [comment]
If only can write that in contract, but can't use in return, maybe cause other confusion for contract developers.

**Comment by Tommo-L** [comment]
> returntype indicates the return type of the method. It can be one of the following values: Signature, Boolean, Integer, Hash160, Hash256, ByteArray, PublicKey, String, Array, InteropInterface, Void.  https://github.com/neo-project/proposals/blob/master/obsolete/nep-3.mediawiki

Our ABI has already defined the `returnType`, which dose not support multiple return.

**Comment by Tommo-L** [comment]
> If only can write that in contract, but can't use in return, maybe cause other confusion for contract developers.

Therefore, it's better for us not support multiple return in c# contract.

**Comment by erikzhang** [comment]
If you allow multiple return in public methods, languages that do not support multiple return values will not be able to call these contracts. So we have to disable it for public methods.

**Comment by devhawk** [comment]
cc @roman-khimov and @fyrchik 

What is the use case for multiple return values as @Shargon [describes here](https://github.com/neo-project/neo-debugger/issues/17#issuecomment-612769751)? If that VM construct doesn't map well enough to existing programming languages, maybe we should model multiple return types as a NeoVM Array. We can map such arrays to language specific constructs (go multi return types, python tuple, C# ValueTuple, etc. I believe the neo-go folks originally implemented multi return types as a NeoVM Array.

**Comment by devhawk** [comment]
@erikzhang, @lightszero Can either of you provide perspective on NeoVM's existing multiple return value support as I mentioned in [my last comment](https://github.com/neo-project/neo-devpack-dotnet/issues/243#issuecomment-613464076)

**Comment by erikzhang** [comment]
For public methods, that is, those methods that must be described in the ABI file, they must have a single return value or no return value (void). If you need multiple return values, you must wrap them in an array or structure. For private methods, the compiler can return up to 127 values according to the syntax.

**Comment by devhawk** [comment]
@erikzhang Do contracts have public methods other than the main entry point?

**Comment by erikzhang** [comment]
There is no entry point anymore.

**Comment by devhawk** [comment]
> There is no entry point anymore.

Are there docs on this? I'm using the [domain sample contract](https://docs.neo.org/docs/en-us/sc/sample/Domain.html) for test purposes. Since it was originally developed for neo2, it has a main entrypoint. What would the equivalent neo3 contract look like? Are there other sample neo3 contracts I could use for test purposes?

**Comment by shargon** [comment]
You only need to remove the `main` method. Now the main `switch ` it's not required

**Comment by Tommo-L** [comment]
Hi, @devhawk  You can see the NEP5-template, it's already adjusted. 
https://github.com/neo-project/neo-devpack-dotnet/blob/master/templates/Template.NEP5.CSharp/NEP5.cs
