### ISSUE TITLE
Modify optimizer of `Parser_DeleteDeadCode`

### ISSUE THREAD

**Issue by ShawnYun** [neo-project/neo-devpack-dotnet#246]
Now if we use abi offset, we will remove the automain method. The  optimizer  can't  find all method entry points. So we will modify it later.

**Comment by ShawnYun** [comment]
Functions' entrypoint address convert becomes very complicated if we use the optimizer `Parser_DeleteDeadCode`, and I recommend using only `DeleteNop` without `Parser_DeleteDeadCode`, which is more concise.

**Comment by shargon** [comment]
Maybe we should add another `INefItem` for method offset, but we should be able to do that.

**Comment by ShawnYun** [comment]
Yes, I will try it.
