### ISSUE TITLE
Make the contract stateful

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-devpack-dotnet#254]
I think when a contract deployed in blockchain, it'll have state. There is an example.

`a` will be persisted in blockchain, it'll increase 1 every time when we invoke `Inc` method.

```cs
contract A{
    int a = 0;
 
    public Inc(){
        return ++a;
   }
}
```

TODO
- [ ] store contract variables in storage

**Comment by shargon** [comment]
This is like ethereum works, without static variables and methods, like a real class, but then have no sense to have a constructor in the blockchain, we should do like they do, execute it during deploy, and remove it from the script.

**Comment by shargon** [comment]
And this could be incompatible with state less executions...

**Comment by Tommo-L** [comment]
> but then have no sense to have a constructor in the blockchain

It's ok for me, remove constuctor.

**Comment by Tommo-L** [comment]
> And this could be incompatible with state less executions...

I think we can make compiler be compatible.

**Comment by shargon** [comment]
> I think we can make compiler be compatible.

How if the value will be in the storage?
