### ISSUE TITLE
Optimizer doesn't work with the last ABI changes

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-devpack-dotnet#256]
OptimizeParserType.DELETE_DEAD_CODE doesn't work with the last ABI changes

https://github.com/neo-project/neo-devpack-dotnet/pull/252/files#r415749579

**Comment by Tommo-L** [comment]
Related  https://github.com/neo-project/neo-devpack-dotnet/issues/246

@ShawnYun will help fix optimizer. As ABI pr is too large, we need another pr to fix optimizer.

**Comment by shargon** [comment]
Closed because it's duplicated
