### ISSUE TITLE
Exception "Syscall not found" when deploy contract

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-devpack-dotnet#257]
### Describe
My contract using the `Crypto.ECDsaVerify` or `Crypto.ECDsaCheckMultiSig` API, it will throw exception "Syscall not found d46a900a"  when deploy contract.

### Version
- neo-devpack-dotnet:https://github.com/neo-project/neo-devpack-dotnet/tree/0c68a4f589dab8fb9c2352259acd6e28523441df
- neo:https://github.com/neo-project/neo/tree/0c94a678d7a152c0b8d90f45459cfe4a4e0a0bad

### Screenshots
![image](https://user-images.githubusercontent.com/12728872/80444415-4d8ba400-8944-11ea-8169-1f47d5a208ea.png)

![image](https://user-images.githubusercontent.com/12728872/80444808-36998180-8945-11ea-9233-b8ced6cd1416.png)

**Comment by shargon** [comment]
We renamed this syscall here https://github.com/neo-project/neo/pull/1419

**Comment by ProDog** [comment]
> We renamed this syscall here [neo-project/neo#1419](https://github.com/neo-project/neo/pull/1419)

OK, thanks!

**Comment by shargon** [comment]
It could be closed?

**Comment by ProDog** [comment]
Need to wait for update `Neo.SmartContract.Framework`?
