### ISSUE TITLE
An contract deploy exception of Enumerator<int> or Enumerator<string>...

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-devpack-dotnet#272]
If the contract contains return Enumerator\<int> or Enumerator\<string>, an exception will be thrown when the deploy contract.

Contract like :
```C#
        public static Enumerator<int> GetEnumerator()
        {            
            var enumerator = Enumerator<int>.Create(new int[3] { 4, 6, 8 });
            return enumerator;
        }
```

The exception when deploy :

![image](https://user-images.githubusercontent.com/12728872/82869668-3d75dd00-9f61-11ea-9948-e7f89b67baaf.png)

Enumerator\<string>, Enumerator\<BigInteger>, Enumerator\<long> have the same exception.

**Comment by ShawnYun** [comment]
I will help to fix it.
