### ISSUE TITLE
Contract_MultipleContracts test generates invalid .manifest.json 

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#277]
If you compile `tests\Neo.Compiler.MSIL.UnitTests\TestClasses\Contract_MultipleContracts.cs` with the current master head of neon, the generated `Contract_MultipleContracts.abi.json` file is empty and the generated `Contract_MultipleContracts.manifest.json` file is invalid

**Comment by ShawnYun** [comment]
The contract should not be compiled correctly and should return an error.
