### ISSUE TITLE
neo-devpack-dotnet version compatibility for NEP-5 contract

### ISSUE THREAD

**Issue by MatthewShelby** [neo-project/neo-devpack-dotnet#280]
hello fellas;
I'm trying to Create a NEP-5 smart contract;
I use this [instruction](https://docs.neo.org/v3/docs/en-us/sc/gettingstarted/develop.html);

At some point it says:
![2020-06-01 23_56_50-Compiling a contract sample](https://user-images.githubusercontent.com/47936625/83446363-c8743d00-a463-11ea-9266-38464718380f.png)

I tried to use [these projects](https://github.com/neo-project/neo-devpack-dotnet/tree/master/src) to build my contract ( and supply things before build, like the framework and...).

Now the problem I have is that the result of building the contract is not the same as expected,(as pointed in instruction).
![2020-06-02 00_05_25-Compiling a contract sample](https://user-images.githubusercontent.com/47936625/83446955-dbd3d800-a464-11ea-99bc-082b755f1556.png)

The instruction said it must generate .nef file but all I have are .avm;
![avm](https://user-images.githubusercontent.com/47936625/83447391-9bc12500-a465-11ea-9df3-82b25c41a680.png)

I tried to use [these projects](https://github.com/neo-project/neo-devpack-dotnet/tree/master/src) to build my contract ( and supply things before build, like the framework and...).

**Are these [projects ](https://github.com/neo-project/neo-devpack-dotnet/tree/master/src)for Neo 3.x???**

**Comment by Tommo-L** [comment]
> Are these projects for Neo 3.x???

Yes.  Check neon whether is the latest version? If not, you can download from https://github.com/neo-project/neo-devpack-dotnet/releases

![image](https://user-images.githubusercontent.com/43396869/83471740-0e5af080-a4b8-11ea-94f5-362fe1e0e2b5.png)

**Comment by MatthewShelby** [comment]
### To inform other users:

The cause of the problem was a conflict between paths that are defined in system environment variables.
There was an old path which conducts PowerShell to an older version of neon.exe. The old path should be removed.

![1399-03-13 16_26_54-Edit environment variable](https://user-images.githubusercontent.com/47936625/83517391-0e75e300-a4ee-11ea-8109-79b7d82d527f.png)

Delete the older one and also check all existing paths to avoid conflict.

**Comment by Tommo-L** [comment]
Thank you, I'll update the docs https://github.com/neo-project/docs/pull/1081

**Comment by Tommo-L** [comment]
@shargon  Could help close this issue, we have already updated the docs.  @MatthewShelby if you have another issue, you can open a new ISSUE.
