### ISSUE TITLE
An exception of Iterator<byte, byte>.Create()

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-devpack-dotnet#282]
If the contract contains `Iterator<byte, byte>.Create(new byte[] { 5 })`, an exception will be thrown when invoke contract.

The `item` Type is `Buffer`:

![image](https://user-images.githubusercontent.com/12728872/83486472-d1a0f080-a4db-11ea-8b00-90a862838ce3.png)

**Comment by Tommo-L** [comment]
As we have converted all string to `Buffer` in C# compiler, which can't be the key of `IIterator `, `Map`. Should we implement the `hashcode` method in neo-vm to support it? @erikzhang

**Comment by shargon** [comment]
Can be converted to a byte array first

**Comment by ShawnYun** [comment]
But we have converted byte[] to `Buffer`, we can't convert it back to `ByteString`.

**Comment by erikzhang** [comment]
c# `string` is converted to `ByteString`. See #291 290

**Comment by Tommo-L** [comment]
Fixed by https://github.com/neo-project/neo/pull/1726
