### ISSUE TITLE
Remove TriggerType from compiler

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-devpack-dotnet#283]
I think we don't need to support TriggerType in compiler now, as we already use the special `verify` method for verification function.

**Comment by shargon** [comment]
We need to filter the syscalls availables in each type

**Comment by Tommo-L** [comment]
That's right, and `System.Runtime.GetTrigger` also use it.

https://github.com/neo-project/neo-devpack-dotnet/blob/4f251bcc6251e56bea2b55465111df0a46072497/src/Neo.SmartContract.Framework/Services/Neo/Runtime.cs#L5-L9
