### ISSUE TITLE
Add returnType when call other contract

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-devpack-dotnet#285]
### Deason
For security reason, it's not safe to call other contract without restrict on the return stack.
```cs
bool verify(int a, int b)
{
    CallSomeContract();
    return a > b;
}
```

```
//script of CallSomeContract()
PUSH 1 // this hide the parameter b of verify()
PUSH 2 // this hide the parameter a of verify()
RET
```

_We expect CallSomeContract() to return no value. But if it maliciously returns 2 values, then these values will be automatically copied onto our stack, causing us to return wrong results. Original posted at  https://github.com/neo-project/neo/pull/1680#discussion_r434484269_

### Solution

~~Maybe we can use the following format:~~

```cs
public static T Contract.Call<T extends StackItem>(B, method, args)
```

---------------------------- update 11 June --------------------------------
Using the following format:

```cs
[Contract(Hash = "0x0011223344556677889900112233445566778899")]
class AContract
{
    public static extern int Funca();
}

[Contract(Hash = "0x0011223344556677889900112233445566778890")]
class BContract
{
    public static extern int Funcb();
}

class MyContract : SmartContract
{
    public static void MyMethod()
    {
        int a = A.Funca()
        int b = B.Funcb();
        a++;
    }
}
```
_original discussed at https://github.com/neo-project/neo/pull/1680#issuecomment-642362337_

**Comment by erikzhang** [comment]
`AppCallAttribute` should be replaced.

**Comment by Tommo-L** [comment]
The parameters of `System.Contract.Call/CallEx` have been updated.
```cs
System.Contract.Call(UInt160 contractHash, ContractParameterType returnType, string method, Array args)
System.Contract.CallEx(UInt160 contractHash, ContractParameterType returnType, string method, Array args, CallFlags callFlags)
```

**Comment by ShawnYun** [comment]
According to https://github.com/neo-project/neo/pull/1706 . We need to modify the plan.
