### ISSUE TITLE
Mapping between C# types and NeoVM types

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo-devpack-dotnet#290]
Supported types
----------------
**C# -> NeoVM**
null -> Null
bool -> Integer
sbyte -> Integer
byte -> Integer
short -> Integer
ushort -> Integer
int -> Integer
uint -> Integer
long -> Integer
ulong -> Integer
BigInteger -> Integer
byte[] -> Buffer
char -> Integer
string -> ByteString
Array -> Array
Enum -> Integer
class -> Array
struct -> Struct
tuple -> Struct
event -> System.Runtime.Notify()
lambda -> Pointer
Delegate -> Pointer | Callback

*Any nullable types will also be mapped to the NeoVM types corresponding to their base types. Because all NeoVM types are nullable.*

Unsupported types
------------------------
float
double
decimal

**Comment by erikzhang** [comment]
Can someone check the implementation of the compiler according to this table?

**Comment by shargon** [comment]
I will create a unit test in dev-pack for ensure this behaviour

**Comment by shargon** [comment]
> event -> System.Runtime.Notify()

We should specify that the arguments are `Array`

**Comment by erikzhang** [comment]
Why array?

**Comment by erikzhang** [comment]
Maybe we should add an `eventName` to `Notify()`.

**Comment by shargon** [comment]
> Maybe we should add an eventName to Notify().

Yes, I will

**Comment by erikzhang** [comment]
@shargon https://github.com/neo-project/neo/pull/1701

**Comment by lightszero** [comment]
fix it https://github.com/neo-project/neo-devpack-dotnet/pull/295
