### ISSUE TITLE
Support byte[].AsString()

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-devpack-dotnet#297]
```cs
public static string testbytearray2(byte[] a)
{
      Map<string, string> some = new Map<string, string>();
     some[a.AsString()] = "teststring2";
     return Json.Serialize(some);
}
```
_posted at https://github.com/neo-project/neo/pull/1710#issuecomment-645947884_

In upper case, we should convert `Buffer` to `ByteString`, as c# byte[] is `NeoVM.Buffer`, c# string is `NeoVM.ByteString`. But the compiler just igore `AsString` method, and return a `Buffer`.

Three problems:
1. Compiler forget to convert `byte[]` in argument parameter list to `Buffer` 
2. `AsString` should convert `Buffer` to `ByteString`.
3.  Map<Primitive, StackItem>, the key of map can only be `Primitive`.

**Comment by erikzhang** [comment]
`Map` should support `string` only.

**Comment by shargon** [comment]
> Map should support string only.

`Primitive` also should support integer and boolean

**Comment by erikzhang** [comment]
@shargon I think c# `bool` should not be supported. Because c# `bool` is actually `int`.
