### ISSUE TITLE
Support callback syscalls

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-devpack-dotnet#299]
Apply https://github.com/neo-project/neo/pull/1629

Support callback syscalls:
- _System.Callback.Create_
- _System.Callback.CreateFromMethod_
- _System.Callback.CreateFromSyscall_
- _System.Callbcak.InvokeCallback_

@shargon Would you add them?

**Comment by erikzhang** [comment]
> System.Callbcak.InvokeCallback

We don't need this in devpack. We should use delegate.

**Comment by shargon** [comment]
> We don't need this in devpack. We should use delegate.

Then how can we distinguish between pointers and `Callbacks`? please take a look to https://github.com/neo-project/neo-devpack-dotnet/pull/302

**Comment by erikzhang** [comment]
One way is we make `System.Callbcak.InvokeCallback` to support both callbacks and pointers.
