### ISSUE TITLE
Always return a value for public methods

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-devpack-dotnet#300]
apply https://github.com/neo-project/neo/pull/1706

- ~~When create a public void method, compiler may return a `Null`.~~
- When call a void method, compiler need to drop the top value on the stack. 

 _We may need to know the ABI of the invoked contract._

**Comment by erikzhang** [comment]
> When create a public void method, compiler may return a Null.

This is wrong.

**Comment by Tommo-L** [comment]
Has already returned a null value in neo-core?

```cs
// neo.SmartContract.ApplicationEngine.cs
protected override void ContextUnloaded(ExecutionContext context)
{
      base.ContextUnloaded(context);
      if (CurrentContext != null && context.EvaluationStack != CurrentContext.EvaluationStack)
          if (context.EvaluationStack.Count == 0)
              Push(StackItem.Null);
}
```

**Comment by shargon** [comment]
Yes, we already return a null item with void

**Comment by ShawnYun** [comment]
But how does the compiler know the return type of the calling contract.

**Comment by erikzhang** [comment]
See https://github.com/neo-project/neo/pull/1680#issuecomment-642100788
