### ISSUE TITLE
An System.ArgumentException when deploy contract

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-devpack-dotnet#308]
My contract like:
```C#
        public static Func<string> CreateFuncPointer()
        {
            return new Func<string>(MyMethod);
        }

        public static string MyMethod()
        {
            return "123";
        }

        public static string CallFuncPointer()
        {
            var pointer = CreateFuncPointer();
            return pointer.Invoke();
        }
```

It will throw an exception when deploy contract, the same problem arises on `Func<int>` `Func<bool>` `Func<byte>`  `Func<object>`  `Func<char>` .

Now only support `Func<BigInteger>` and `Func<byte[]>`.

Exception:

![image](https://user-images.githubusercontent.com/12728872/85381814-ed466680-b570-11ea-9b88-792185a450f0.png)

**Comment by erikzhang** [comment]
The abi file is incorrect.

**Comment by shargon** [comment]
@ProDog  Could you provide the abi ?

**Comment by ProDog** [comment]
abi:
```
        {
            "name":"createFuncPointer",
            "offset":"0",
            "parameters":
            [
            ],
            "returnType":"Unknown:System.Func`1<System.Int32>"
        },
```

**Comment by ShawnYun** [comment]
need fix the return type.

**Comment by ShawnYun** [comment]
@erikzhang  For `System.Func1<System.Int32>`  it should return a `Pointer` . But there seems to be no corresponding type in neo-core?

**Comment by shargon** [comment]
any?

**Comment by erikzhang** [comment]
I think you shouldn't return a `Pointer` if it is a `public` method. Because other contracts can't use the `Pointer`.

**Comment by shargon** [comment]
`CALLA` check that the caller it's the same contract

**Comment by erikzhang** [comment]
I think this can be closed. `Pointer` is not a valid parameter or return type for `public` methods.

**Comment by Tommo-L** [comment]
Agree, it's not safe. One contract can access other contract anywhere by construct a `Pointer(Script ,Position)`.

**Comment by shargon** [comment]
It's the same as a `Callback` but agree, we should use callback instead of pointers for public methods

**Comment by ProDog** [comment]
> `Pointer` is not a valid parameter or return type for `public` methods.

Should the compiler prompt for this situation? such as throwing an exception.
