### ISSUE TITLE
StorageMap can't be written in static variables

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-devpack-dotnet#310]
I found that if StorageMap is written in a global variables, the execution will report an error. 
If the StorageMap is written in a variable in the method, it is executed correctly.

``` c#
[Features(ContractFeatures.HasStorage)]
public class Contract1 : SmartContract
{
    private static readonly StorageMap Data = Storage.CurrentContext.CreateMap("data");

    public static void Put(string message)
    {
        Data.Put(message, Blockchain.GetHeight());
    }

    public static BigInteger Get(string msg)
    {
        return Data.Get(msg)?.ToBigInteger() ?? 0;
    }

    public static void Put2(string message)
    {
        var Data2 = Storage.CurrentContext.CreateMap("data");
        Data2.Put(message, Blockchain.GetHeight());
    }

    public static BigInteger Get2(string msg)
    {
        var Data2 = Storage.CurrentContext.CreateMap("data");
        return Data2.Get(msg)?.ToBigInteger() ?? 0;
    }
}
```

The `put` and `get` methods will fail to execute, but the `put2` and `get2` methods will execute successfully.

**This bug will appear in both Neo2 and Neo3**

The picture below is the execution result:

![image](https://user-images.githubusercontent.com/6295602/85497020-e3c00b80-b60f-11ea-9264-12b2bd6dc8e6.png)

StorageMap 如果写在全局变量（静态变量）中，会执行出错，但写在方法里面就能正常执行，从Neo2到现在一直存在的Bug。为此我还补充了文档。但我觉得有坑的话应该先把坑填上，而不是叫所有人都绕过去走。

![image](https://user-images.githubusercontent.com/6295602/85498161-becc9800-b611-11ea-8577-851847cd1e86.png)

**Comment by shargon** [comment]
Could you take a look @lightszero ?

**Comment by lightszero** [comment]
I think this is about https://github.com/neo-project/neo-devpack-dotnet/issues/237

**Comment by ShawnYun** [comment]
I will check it, but according to the above mentioned, this bug will appear in both Neo2 and Neo3.
