### ISSUE TITLE
Generate contract interface when compile

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-devpack-dotnet#328]
Since we'll use `ContractCall` to replace `Appcall`, we can generate contract interface when compile contract.

The suffix name can be `XXXXX.interface.cs`?

**Comment by shargon** [comment]
is not better to generate it with the ABI?

**Comment by devhawk** [comment]
> is not better to generate it with the ABI?

I agree. NEON should be able to generate C# proxy types from the contract manifest.
