### ISSUE TITLE
Update demo contract

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-devpack-dotnet#351]
https://github.com/neo-project/neo-devpack-dotnet/blob/3ea7af7291fe3800da840ecd1450142f25b196b0/templates/Template.CSharp/Contract1.cs#L6-L20

- add `Verify` method and comment
- change `Main(string operation, object[] args)` to `Main()`
-

**Comment by devhawk** [comment]
Should we also add Update and/or Delete?
