### ISSUE TITLE
How to create growable list/array in C#

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#358]
The `Neo.VM.Types.Array` is implemented as a `List<StackItem>` and has an `Add(StackItem)` method. NeoVM has an APPEND opcode that invokes `Array.Add`. However, there doesn't appear to be a way to create a NeoVM array and append items to it in C#. How does that work?

**Comment by devhawk** [comment]
Should there be an Array equivalent to `Neo.SmartContract.Framework.Map`?

**Comment by devhawk** [comment]
I built this local to my sample project. Probably should be a part of the smart contract framework

``` csharp
public class NeoArray<T> 
{
    [OpCode(OpCode.NEWARRAY0)]
    public extern NeoArray();

    public extern int Count
    {
        [OpCode(OpCode.SIZE)]
        get;
    }

    public extern T this[int key]
    {
        [OpCode(OpCode.PICKITEM)]
        get;
        [OpCode(OpCode.SETITEM)]
        set;
    }

    [OpCode(OpCode.APPEND)]
    public extern void Add(T item);

    [OpCode(OpCode.REMOVE)]
    public extern void RemoveAt(int index);

    [OpCode(OpCode.CLEARITEMS)]
    public extern void Clear();

    public extern T[] Values
    {
        [OpCode(OpCode.VALUES)]
        get;
    }
}
```

**Comment by erikzhang** [comment]
> Should there be an Array equivalent to Neo.SmartContract.Framework.Map?

https://github.com/neo-project/neo-devpack-dotnet/blob/master/src/Neo.SmartContract.Framework/Map.cs

**Comment by erikzhang** [comment]
> I built this local to my sample project. Probably should be a part of the smart contract framework

It looks good. Can you create a pull request?
