### ISSUE TITLE
Remove GetValidators

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-devpack-dotnet#380]
`GetValidators` method is not in NEO, it should be removed.
https://github.com/neo-project/neo-devpack-dotnet/blob/e3d8da36f7ff6eb4854da258f74822b941065c44/src/Neo.SmartContract.Framework/Services/Neo/NEO.cs#L22

**Comment by ProDog** [comment]
And
https://github.com/neo-project/neo-devpack-dotnet/blob/e3d8da36f7ff6eb4854da258f74822b941065c44/src/Neo.SmartContract.Framework/Services/Neo/Policy.cs#L16

**Comment by shargon** [comment]
`GetBlockedAccounts` it was included in https://github.com/neo-project/neo-devpack-dotnet/pull/378 but it's better in other pr
