### ISSUE TITLE
Support add operation between String and Int

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-devpack-dotnet#385]
Support the following case:
```cs
int code = 1
Runtime.Log("oracle response failure with code " + code);
```

**Comment by roman-khimov** [comment]
Maybe some `System.Binary.Itoa` and `System.Binary.Atoi` syscalls for this?

**Comment by Tommo-L** [comment]
> Maybe some `System.Binary.Itoa` and `System.Binary.Atoi` syscalls for this?

It's good for me.

**Comment by Tommo-L** [comment]
Or new opcode `itoa` and `atoi`?

**Comment by shargon** [comment]
Please check https://github.com/neo-project/neo/pull/2043
