### ISSUE TITLE
Smart Contract framework needs JSON types

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#392]
[`Json.Deserialize`](https://github.com/neo-project/neo-devpack-dotnet/blob/dee9b41ab711faea75cc025b06a652705e190893/src/Neo.SmartContract.Framework/Services/Neo/Json.cs#L9) appears to support parsing a string of Json (as would be provided via oracle response) into Neo.IO.Json types. However, there is no equivalent to Neo.IO.Json types in the Smart Contract Framework. How are contracts supposed to interact with deserialized JSON?

**Comment by shargon** [comment]
Already done
