### ISSUE TITLE
Static constructor with local variable is not compiled properly

### ISSUE THREAD

**Issue by csmuller** [neo-project/neo-devpack-dotnet#405]
The neon compiler (version neo3-preview3) allows the usage of static constructors, but it is not compiled correctly when using local variables in the static constructor, as shown in the code example below.

In my tests, the static field `i` was initialized to the value 2 instead of 20.
Local fields in the static constructor should probably be prohibited. At least an compiler exception should be thrown if the developer uses local variables in the static constructor.

```
public class MyContract : SmartContract
{
    private static int i;

    static MyContract() {
        int localInteger = 10;
        i = localInteger * 2;
    }

    public static int main()
    {
        return i;
    }
}
```

**Comment by shargon** [comment]
@lightszero could you take a look please?

**Comment by lightszero** [comment]
we just support code like below when we write this.
so static constructor  is sideeffect.T_T
```
public class MyContract : SmartContract
{
    private static int i = 4;//like this ,this will add a static constructor automatic

    public static int main()
    {
        return i;
    }
}
```
we have to think more about static constructor.

1.first step,I will try to check code in static consturctor and throw it if we can't calc it right.
2.next step,I will try to find a safe way to calc them.
