### ISSUE TITLE
Ship NEON for Neo 3 on nuget.org as a packaged tool

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#411]
Now that we've tagged preview 4, can we publish the preview 4 neo.neon package on nuget.org?

cc @erikzhang @lightszero

**Comment by erikzhang** [comment]
Done.

https://www.nuget.org/packages/Neo.Neon/3.0.0-preview4

**Comment by devhawk** [comment]
Thanks @erikzhang. Can we also do this for neo modules? https://github.com/neo-project/neo-modules/issues/202
