### ISSUE TITLE
Sync with Call Token

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-devpack-dotnet#416]
https://github.com/neo-project/neo-vm/pull/382

**Comment by Tommo-L** [comment]
Will we replace `System.Contract.Call` by `CALLT`?

**Comment by cloud8little** [comment]
@shargon

**Comment by shargon** [comment]
If no one is working on it, I will start it today

**Comment by shargon** [comment]
Wait for https://github.com/neo-project/neo-devpack-dotnet/pull/414

**Comment by shargon** [comment]
@erikzhang we should use `CALLT` only for native contracts right? otherwise it's a state dependant compilation

**Comment by erikzhang** [comment]
It should be used for all static calls.
