### ISSUE TITLE
Can't run in VS2019

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-devpack-dotnet#43]
![image](https://user-images.githubusercontent.com/6295602/56885968-77e02280-6aa0-11e9-9f6a-e1360a041faa.png)
在 VS2019 中编译智能合约会报错，解决办法是编译 neo-devpack-dotnet 项目，将生成的 Neo.SmartContract.Framework.dll 替换掉原有的文件。

Compile smart contract error in VS2019, solution is to compile the neo-devpack-dotnet project, and replace Neo.SmartContract.Framework.dll file to the existing file.

**Comment by chenzhitong** [comment]
@steven1227

**Comment by lightszero** [comment]
I think this issue can be closed now.

**Comment by erikzhang** [comment]
@chenzhitong Can you confirm that this issue has been solved?

**Comment by chenzhitong** [comment]
![image](https://user-images.githubusercontent.com/6295602/60382833-39b0b080-9a9b-11e9-885f-72f3b810caf6.png)


![image](https://user-images.githubusercontent.com/6295602/60382895-58fc0d80-9a9c-11e9-9b6a-ad1d953e3b53.png)


There are still errors, I used the latest neon and neo-devpack-dotnet code

**Comment by chenzhitong** [comment]
![image](https://user-images.githubusercontent.com/6295602/60382917-bee89500-9a9c-11e9-9a41-afc26b9cca38.png)

This is the error when run neon directly.

**Comment by lightszero** [comment]
is this pr https://github.com/neo-project/neo-devpack-dotnet/pull/48 ?
need update

**Comment by lightszero** [comment]
Build template had be removed.
did you test https://github.com/neo-project/examples ?

**Comment by lock9** [comment]
This was fixed on #121
