### ISSUE TITLE
BigInteger.Parse Issue

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-devpack-dotnet#431]
Use BigInteger.Parse does not work.

![f8fa6bce1fe692a28af893696dee24e](https://user-images.githubusercontent.com/34291844/104703967-fdaf7000-5752-11eb-9a0f-fb16ccc83f8e.png)

![55244b3ab4c875c83e2ea96acae3f45](https://user-images.githubusercontent.com/34291844/104703982-03a55100-5753-11eb-83b0-7fc306c4bc38.png)

**Comment by shargon** [comment]
Could you detail the issue?

**Comment by ProDog** [comment]
The contract doesn't seem to support `BigInteger.Parse(string)`.

**Comment by cloud8little** [comment]
> The contract doesn't seem to support `BigInteger.Parse(string)`.

https://github.com/neo-project/neo-devpack-dotnet/blob/3c01c3eb179072e9365f50340f4bcb8ca071cd80/tests/Neo.Compiler.MSIL.UnitTests/UnitTest_StaticVar.cs#L49-L58

**Comment by shargon** [comment]
I will fix it in https://github.com/neo-project/neo-devpack-dotnet/pull/433

**Comment by shargon** [comment]
Could you check https://github.com/neo-project/neo-devpack-dotnet/pull/433/commits/e113903f4fe950f022e28cdb4596b14a9ab7bf1d it seems that it works.

Do you know if it's stored in your contract as string ?
