### ISSUE TITLE
SYSCALL Unknown when deal with onPayment

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-devpack-dotnet#436]
1. deploy NEP17 template contract.  (https://github.com/neo-project/examples/pull/33)
2. invoke enablePayment
3. open neo to the contract address.

![a68f65499d1da92e5e7db5413f29944](https://user-images.githubusercontent.com/34291844/104747250-4256fd80-578b-11eb-8421-7cc3d904b484.png)

![22de03674006e1211969349833c20a3](https://user-images.githubusercontent.com/34291844/104747270-484cde80-578b-11eb-8ec2-4c86e7ce92b4.png)

![358d06ea2a2d34ffb68bba6b9bced5f](https://user-images.githubusercontent.com/34291844/104747289-4daa2900-578b-11eb-8866-084073f64bb1.png)

![0f6af1ce5db1f968363f54a9fe33d88](https://user-images.githubusercontent.com/34291844/104747489-8ea23d80-578b-11eb-83ad-670186f44719.png)

It seems the Operand can not be analyzed correctly, not sure if this is compiler issue. Let's figure out why and then put the issue to the right repository.

**Comment by erikzhang** [comment]
What is the value of `value`?

**Comment by cloud8little** [comment]
> What is the value of `value`?

\u0001

**Comment by shargon** [comment]
We should unify the key

![image](https://user-images.githubusercontent.com/3167973/104810640-51bf6080-57f6-11eb-86f2-f2e1a7e51a7f.png)

instead of `ToBigInteger` we should use a cast, isn't it?

**Comment by cloud8little** [comment]
@shargon you're right. close this because it is also caused by BigInteger.Parse.
