### ISSUE TITLE
how to use on linux to compile smartcontract ?

### ISSUE THREAD

**Issue by djm34** [neo-project/neo-devpack-dotnet#441]
Hello, 
is it possible to use that package on linux (and how). 
I have used a bit neo-compiler but apparently neo-compiler doesn't support neo3-preview (?)

Thanks for your help

**Comment by vncoelho** [comment]
Hi @djm34,

https://neocompiler.io/#nav-compilers/ has been updated recently, but not yet stable.
We are still adjusting deploy and invoke functionalities, creating a specific tab that manages `NativeContracts` operations.

But I believe that you can already use it to compile codes following master, current commit of our online version is https://github.com/neo-project/neo-devpack-dotnet/commit/c7e0f0349a6a39bc188acecb4f5c2e66340de583.

**Comment by devhawk** [comment]
https://github.com/devhawk/registrar-sample works on linux and windows

**Comment by djm34** [comment]
Hello, 
thanks for the answers. 
yeah, I am more interested in a way to compile/deploy/manage contract in a way as  automated as possible... hence on linux. 
However if it is possible to submit through API something to neocompiler it could be an interesting alternative too
I will have a look to these 2 projects,
thanks again,
djm34
