### ISSUE TITLE
Syntax checking bug on Storage.Put(Storage.CurrentContext, string, string)

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-devpack-dotnet#443]
**code:**
```c#
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;

namespace StorageExample
{
    [ManifestExtra("Author", "Neo")]
    [ManifestExtra("Email", "dev@neo.org")]
    [ManifestExtra("Description", "This is a contract example")]
    public class Contract1 : SmartContract
    {
        public static void put() => Storage.Put(Storage.CurrentContext, "hello", "world");
        public static void get() => Storage.Get(Storage.CurrentContext, "hello");
    }
}
```

The compilation **should not pass** here, because an overloaded method (`void Put(Neo.SmartContract.Framework.Services.Neo.StorageContext context, string key, string value)`) is missing
![image](https://user-images.githubusercontent.com/6295602/105794137-5db0dc80-5fc5-11eb-8c71-ce2c73f5d3ab.png)

However, it will compile and pass, but the deployment will report an error
![image](https://user-images.githubusercontent.com/6295602/105794017-22aea900-5fc5-11eb-8942-f996004a4a2b.png)

**Suggestions:** 
Add overloaded methods `void Put(Neo.SmartContract.Framework.Services.Neo.StorageContext context, string key, string value)`
Or fix syntax checking bugs

**Comment by erikzhang** [comment]
You need to provide the `StackTrace` of the exception to report the bug. @chenzhitong

**Comment by chenzhitong** [comment]
Deleting the old blockchain files and redeploying, it worked
