### ISSUE TITLE
return type for Iterator is IInteropInterface 

### ISSUE THREAD

**Issue by bettybao1209** [neo-project/neo-devpack-dotnet#447]
![image](https://user-images.githubusercontent.com/12050350/106255499-10e33500-6255-11eb-819d-712b8fe87021.png)

Since the return type `Iterator ` in nameservice is compiled into `IInteropInterface ` rather than `InteropInterface`, so it fails to deploy the contract.

**Comment by shargon** [comment]
Coud you send the manifest?

**Comment by shargon** [comment]
Please check if https://github.com/neo-project/neo-devpack-dotnet/pull/448 fix this issue

**Comment by bettybao1209** [comment]
> Please check if #448 fix this issue

It works for this case.

**Comment by bettybao1209** [comment]
Also, it needs to sync https://github.com/neo-project/neo/pull/2271

**Comment by shargon** [comment]
> Also, it needs to sync neo-project/neo#2271

We have this https://github.com/neo-project/neo-devpack-dotnet/pull/446
