### ISSUE TITLE
[Question] Storage Get and Put for Preview5

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-devpack-dotnet#456]
Previously, we had to efforts to remove the parameter `Storage.CurrentContext` from both calls.

Are there other `Context` that we may access nowadays, right (such as calling other allowed contracts)? 
In such case, `Storage.Get(Storage.CurrentContext, "Hello");` should be kept like that. Otherwise, we could simplify it and we did in the past.

**Comment by erikzhang** [comment]
Now you can use the "storage-backed properties". See #745
