### ISSUE TITLE
About UInt160.IsValid

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-devpack-dotnet#458]
https://github.com/neo-project/neo-devpack-dotnet/blob/01fe0f6cd9cdf66c858b41c90540c3e700874a8f/src/Neo.SmartContract.Framework/UInt160.cs#L3-L27

```c#
private static bool ValidateAddress(UInt160 address) => address.IsValid;
```

If an object is already of type `UInt160`, then why do we need to determine `IsValid`? @shargon

**Comment by erikzhang** [comment]
Because `UInt160` is a high level type. The underlying type in vm is `ByteString`. We have to check it.
