### ISSUE TITLE
[Suggestion] automatically add permissions?

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-devpack-dotnet#475]
If permission is not added, an error will occur when the contract is upgraded and destroyed. 
This is because it calls the `ContractManagement` native contract, but does not declare permissions.

Solutions:

1. The compiler automatically adds permissions when it detects code that calls a native contract.
2. Add ContractManagement to the permissions by default.
2. Do nothing, Let the developer add it manually.
3. Let the developer add it manually. And permissions supports adding the contract name of the native contract, because there is no guarantee that the hash of the native contract will not change (it has already changed n times).

Which is better?

**Comment by shargon** [comment]
I think that option 2 it's good
