### ISSUE TITLE
Support ToByteArray() overload

### ISSUE THREAD

**Issue by Lichen9618** [neo-project/neo-devpack-dotnet#502]
```C#
public byte[] ToByteArray();  
public byte[] ToByteArray(bool isUnsigned = false, bool isBigEndian = false);
```

Version: System.Runtime.Numerics, Version=5.0.0.0, Culture=neutral
BigInteger support two ToByteArray() method.

In our  latest compiler(2021/4/3), only first one has been supported.
Can we try two support both _ToByteArray_ method?

**Comment by erikzhang** [comment]
After discussion, we do not intend to implement it.
