### ISSUE TITLE
Check null should return 

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-devpack-dotnet#527]
```cs
            var value = StorageGet(key);
            if (value?.Length > 0)
            {
                StorageDelete(key);
                onRemoveExchange(tokenA, tokenB);
            }
```

![baafbd73537219e3ab6722b5ed17c03](https://user-images.githubusercontent.com/34291844/114002837-d23eac00-988f-11eb-8f55-301c2d481428.png)

![8e5827c7fd0a5012901451f5ebad9e2](https://user-images.githubusercontent.com/34291844/114002986-f9957900-988f-11eb-82ff-cb524abafda7.png)

![c47ca96fed5122a86921554b0a56ba3](https://user-images.githubusercontent.com/34291844/114002999-fb5f3c80-988f-11eb-9d08-1cff76ab7792.png)

the same with >, <, >=, <=

**Comment by shargon** [comment]
@cloud8little could you modify the test from https://github.com/neo-project/neo-devpack-dotnet/pull/528 to replicate the issue? It works for me
