### ISSUE TITLE
Contract_OptimizationTest has invalid ToScriptHash call

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#538]
`Helper.ToScriptHash` has been removed.

``` csharp
private static Neo.UInt160 Owner = "Ne9ipxm2sPUaetvh3ZvjhyCzRZqP355dTZ".ToScriptHash();
```

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-devpack-dotnet/blob/eb7359866d65799086b9c9d1862902982650dd52/src/Neo.SmartContract.Framework/InitialValueAttribute.cs#L6

Please use `InitialValueAttribute`.

**Comment by devhawk** [comment]
The test contract should be updated or removed
