### ISSUE TITLE
nccs provides no error location information 

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#539]
When the C# compilation step succeeds but the C# -> NEOVM step fails, we get no information about where in the code the error is located. 

Example error output: 

``` shell
$ nccs .\OwnerContract.csproj
  Determining projects to restore...
  All projects are up-to-date for restore.
error NC1002: Unknown method: System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo, System.Type)
```

**Comment by shargon** [comment]
Could you provide an example, in my test I get the line

![image](https://user-images.githubusercontent.com/3167973/114363627-df51e880-9b78-11eb-8387-38750634dfae.png)

**Comment by devhawk** [comment]
I guess I must of hit a case where the source location wasn't getting surfaced. Since #541 is fixed, I'll close this issue. If I hit this anywhere else, I'll reopen w/ a better repro
