### ISSUE TITLE
Create NccsTask for MSBuild

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#551]
Instead of attempting to replicate the msbuild logic for calculating the list of source files and metadata references of a contract project, nccs should simply depend on msbuild to calculate this info and pass it to nccs on the command line. the main C# compiler has the [CscTask msbuild task](https://docs.microsoft.com/en-us/visualstudio/msbuild/csc-task) that accepts the list of references + source files and calculates the command line to pass to csc.exe. If we build a similar NccsTask, we could remove the .csproj parsing logic from nccs

**Comment by erikzhang** [comment]
Where should NccsTask be implemented? Neo.SmartContract.Framework?

**Comment by devhawk** [comment]
Next version of neo.buildTools will have this. https://github.com/ngdenterprise/neo-test/blob/main/src/build-tasks/NeoCsc.cs

We need to move this repo over to neo project. Might make sense to move this specific package into this repo. Let me know if you want me to do that

**Comment by erikzhang** [comment]
Once we have this project, how to register the tasks in MSBuild? I know we can use `UsingTask` to register them. But I don't think it's a good idea to copy the `neo-build-tasks.dll` to every contract project.

So, I think maybe we should move the tasks to `Neo.SmartContract.Framework`. Because every contract project will reference it through nuget.

**Comment by devhawk** [comment]
> Once we have this project, how to register the tasks in MSBuild? I know we can use `UsingTask` to register them. But I don't think it's a good idea to copy the `neo-build-tasks.dll` to every contract project.
> 
> So, I think maybe we should move the tasks to `Neo.SmartContract.Framework`. Because every contract project will reference it through nuget.

MSBuild task assemblies must be compatible with netstandard2.0 and net461, so can't put it in the same assembly as the contract framework. But it's also not necessary. You can in include MSBuild props and target files in the nuget package. Example: https://github.com/ngdenterprise/neo-test/blob/main/src/build-tasks/build/Neo.BuildTasks.targets

**Comment by devhawk** [comment]
You can see this in action using [devhawk/buildtool](https://github.com/ngdenterprise/neo-registrar-sample/tree/devhawk/buildtool ) branch of the Registrar sample. This will get merged after 3.3 ships.

The root `Directory.Build.props` file adds the BuildTasks nuget package to all projects in the solution. THe `PrivateAssets="All"` attribute indicates this package is used at compile time, not run time. 

``` xml
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <NeoTestPackagesVersion>3.2.10-preview</NeoTestPackagesVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Neo.BuildTasks" Version="$(NeoTestPackagesVersion)" PrivateAssets="All" />
    </ItemGroup>
</Project>
```

NCCS compilation is triggered automatically for all projects that specify the `NeoContractName` property element:

``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NeoContractName>$(AssemblyName)</NeoContractName>
    <NeoExpressBatchFile>..\express.batch</NeoExpressBatchFile>
    <Nullable>enable</Nullable>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Neo.SmartContract.Framework" Version="3.1.0" />
  </ItemGroup>

</Project>
```

**Comment by erikzhang** [comment]
https://github.com/ngdenterprise/neo-registrar-sample/blob/04c990db7877c5f7c94fd6af5c505c4af418d15d/Directory.Build.props#L8

We need to add it to `Neo.SmartContract.Template`.

**Comment by erikzhang** [comment]
> We need to move this repo over to neo project. Might make sense to move this specific package into this repo. Let me know if you want me to do that

I think it's necessary.

**Comment by devhawk** [comment]
> > We need to move this repo over to neo project. Might make sense to move this specific package into this repo. Let me know if you want me to do that
> 
> I think it's necessary. But do we need that many tasks? I think we only need `NeoCsc`.

Neo BuildTools is in the NeoTest repo because the initial build tool was `NeoContractInterface`, a tool that generates a C# interface from the Neo contract manifest for test purposes. Let's you write test code like this:

``` cs
engine.ExecuteScript<NeoContributorToken>(c => c.mint("Test Contributor", "Test Description", "https://i.picsum.photos/id/856/500/500.jpg?hmac=BOzGgyuyo7weE0xNPxJ_8cw3I7oWUwIiHRN_Y51EoNs"));
```

The delegate gets passed to `ExecuteScript<contract-name>` as an `Expression` tree, which can then be [converted into NeoVM script](https://github.com/ngdenterprise/neo-test/blob/main/src/test-harness/Extensions.cs#L61-L78). I think it's a much simpler way to write contract invocations than using `scriptBuilder.EmitDynamicCall` and it's typesafe to boot. We might want to consider something similar for a C# Neo dApp library. 

The `NeoContractInterface` generates a C# interface that is used to define the typesafe contract methods that `ExecuteScript<contract-name>` uses. That task has shipped in BuildTools for several releases. Removing it would be a breaking change. 

The only other tool in BuildTools currently is NeoExpressBatch, which is going to be critical for blockchain toolkit users. Plus, NeoExpressBatch and NeoCsc tasks both share common code in DotNetToolTask, so it would be difficult to separate them.

We could create a new package for NeoCsc + NeoExpressBatch since those are new in the ~3.2~ 3.3 toolkit release. But the enitre BuildTools package size for 3.3 is only 51kb (built on my laptop, release build). Hardly seems worth it to break into separate packages.
