### ISSUE TITLE
NCCS Documentation?

### ISSUE THREAD

**Issue by wschae** [neo-project/neo-devpack-dotnet#558]
Hi Team,

Can you point to any documentation on nccs.exe? I guess that it has replaced neon.exe. It would be great to see some documentation or roadmap of this change 👍 Although it was limited, neon.exe has supported VB and F# (through dll) and I am wondering if the team will focus on C#.

**Comment by erikzhang** [comment]
> Can you point to any documentation on nccs.exe?

There is currently no documentation for nccs. Can you clarify what type of document you want? We will add as soon as possible.

> I am wondering if the team will focus on C#.

There are currently no plans to support VB and F#. Before Roslyn provides a more complete `IOperation` API, we will focus on C#.

**Comment by wschae** [comment]
Something like this (https://docs.neo.org/docs/en-us/gettingstarted/develop.html) would be enough. I am following the document to know how to use it and found no document on nccs.exe (could be too early 😅) 

Thanks for clarification on C#. Sounds reasonable to me and I can see a lot of efforts to move from mono to Roslyn. Can I assume that there will be no more neon.exe in NEO 3?

**Comment by erikzhang** [comment]
> Something like this

@neo-project/ngd-shanghai Please update the docs.

> Can I assume that there will be no more neon.exe in NEO 3?

Yes.

**Comment by devhawk** [comment]
Are we still telling developers to compile the dev tools locally instead of simply installing them using dotnet tool install? https://docs.neo.org/docs/en-us/gettingstarted/develop.html

**Comment by erikzhang** [comment]
@neo-project/ngd-shanghai

**Comment by steven1227** [comment]
OK. We will update.

**Comment by Ashuaidehao** [comment]
> Are we still telling developers to compile the dev tools locally instead of simply installing them using dotnet tool install? https://docs.neo.org/docs/en-us/gettingstarted/develop.html

Please check this:  https://docs.neo.org/docs/en-us/gettingstarted/develop.html#using-visual-studio-code-to-develop

**Comment by devhawk** [comment]
> Please check this: https://docs.neo.org/docs/en-us/gettingstarted/develop.html#using-visual-studio-code-to-develop

Very nice! Question: is there a repo for the Neo3.SmartContract.Templates ?

**Comment by Ashuaidehao** [comment]
> > Please check this: https://docs.neo.org/docs/en-us/gettingstarted/develop.html#using-visual-studio-code-to-develop
> 
> Very nice! Question: is there a repo for the Neo3.SmartContract.Templates ?
Here it is:
https://github.com/neo-ngd/Neo3.SmartContract.Templates

**Comment by shargon** [comment]
@neo-project/ngd-shanghai In https://docs.neo.org/docs/en-us/gettingstarted/develop.html#using-visual-studio-code-to-develop doesn't appear the line `dotnet tool install --global Neo.Compiler.CSharp --version 3.3.0`
