### ISSUE TITLE
Return help information when using nccs without any argument or option.

### ISSUE THREAD

**Issue by nicolegys** [neo-project/neo-devpack-dotnet#560]
When I enter "nccs" without any argument or option at the terminal, it will work on the current path by default, and throw exception. 
![image](https://user-images.githubusercontent.com/43694095/114665377-89737100-9d2f-11eb-8d52-732f21f4112f.png)

I think we should return help information in this case, just like `dotnet`
![image](https://user-images.githubusercontent.com/43694095/114665660-e2dba000-9d2f-11eb-81c8-f9e15eff263d.png)

**Comment by erikzhang** [comment]
If no parameter is provided, it will compile the `.csproj` file in the current directory. You can use `--help` to show the help information.

**Comment by cloud8little** [comment]
> If no parameter is provided, it will compile the `.csproj` file in the current directory. You can use `--help` to show the help information.

for better experience, it should show help info in this case, because lots of new-learners will just input the command nccs to know how it works. and if it accidently run the command in a parent folder which contains lots of csproj file, it is a disaster.

**Comment by chenzhitong** [comment]
For new developers, after configuring the environment variable path, type `nccs` on the command line in any location to check if the configuration is correct. It is very unfriendly to report errors directly at this point.

**Comment by ProDog** [comment]
In addition, some log information is needed when compiling, and this is the only output now:
```
PS D:\TestCode\Neo3Contract\Neo3Contract> dotnet D:\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\bin\Debug\net5.0\nccs.dll .\Neo3Contract.csproj
  正在确定要还原的项目…
  所有项目均是最新的，无法还原。
PS D:\TestCode\Neo3Contract\Neo3Contract>
```
No way to know whether really successful compilation.

**Comment by shargon** [comment]
@ProDog please check https://github.com/neo-project/neo-devpack-dotnet/pull/562/commits/cf12556d8dbc0a3e77b57fbe86d60bcd66ee342a

**Comment by ProDog** [comment]
It's OK:
```
PS D:\TestCode\Neo3Contract\Neo3Contract> dotnet D:\neo_code\neo-devpack-dotnet\src\Neo.Compiler.CSharp\bin\Debug\net5.0\nccs.dll .\Neo3Contract.csproj
  正在确定要还原的项目…
  所有项目均是最新的，无法还原。
D:\TestCode\Neo3Contract\Neo3Contract\MyContract.cs(34,36): warning CS0108: “MyContract.OnNotify”隐藏继承的成员“Nep11Token<Nep11TokenState>.OnNotify”。如果是有意隐藏，请使用关键字 new。
D:\TestCode\Neo3Contract\Neo3Contract\MyContract.cs(65,28): warning CS0108: “MyContract.Burn(ByteString)”隐藏继承的成员“Nep11Token<Nep11TokenState>.Burn(ByteString)”。如果是有意隐藏，请使用关键字 new。
D:\TestCode\Neo3Contract\Neo3Contract\MyContract.cs(31,30): warning CS0108: “MyContract.Notify”隐藏继承的成员“Nep11Token<Nep11TokenState>.Notify”。如果是有意隐藏，请使用关键字 new。
Created D:\TestCode\Neo3Contract\Neo3Contract\bin\sc/MyTestContract.nef
Created D:\TestCode\Neo3Contract\Neo3Contract\bin\sc/MyTestContract.manifest.json
Compilation completed successfully. The target files have been generated in "D:\TestCode\Neo3Contract\Neo3Contract\bin\sc".
PS D:\TestCode\Neo3Contract\Neo3Contract>
```

**Comment by steven1227** [comment]
We need fix this. Almost 99% of modern tools will display log when you did not append arguments.
