### ISSUE TITLE
FindOptions.RemovePrefix only removes one byte size of prefix

### ISSUE THREAD

**Issue by bettybao1209** [neo-project/neo-devpack-dotnet#563]
Since RemovePrefix only removes the first byte of the key as defined in https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/Iterators/StorageIterator.cs#L35
 
Then for https://github.com/neo-project/neo-devpack-dotnet/blob/master/src/Neo.SmartContract.Framework/Services/Storage.cs#L89, if we set FindOptions.RemovePrefix,  it seems the prefix cannot be truely removed. Is it intended?

**Comment by erikzhang** [comment]
We only remove the first byte.

**Comment by erikzhang** [comment]
@bettybao1209 I think it is possible to remove the full prefix. I will create a PR.
