### ISSUE TITLE
CSharp compiler missing hash value

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#566]
From [NDX-DN11 - NEO Debug Info Specification}(https://github.com/ngdenterprise/design-notes/blob/master/NDX-DN11%20-%20NEO%20Debug%20Info%20Specification.md#v11-format)

> For Neo 3 contract debug info, hash property is required

Even though Neo 3 no longer uses the script hash for invocation, the debugger still uses it to associate debug info with NEF file script contents.

**Comment by erikzhang** [comment]
The compiler lacks the `Transaction.Sender` field necessary to calculate the hash.

**Comment by devhawk** [comment]
This value is not the invocation hash, it's purely the script hash, calculated by `Neo.SmartContract.Helper.ToScriptHash`

**Comment by erikzhang** [comment]
Will this not cause confusion?

**Comment by devhawk** [comment]
> Will this not cause confusion?

I don't see why it would, it's stored inside the .nefdbgnfo file and only used inside the debugger implementation. 

Even if it was confusing, the debugger needs a way to ensure the debug info is associated with the correct version of the contract script. Contracts compiled by nccs are not debuggable without it

**Comment by erikzhang** [comment]
What about use a guid?

**Comment by devhawk** [comment]
> What about use a guid?

Needs to be deterministic + the debugger already is implemented this way.
