### ISSUE TITLE
ProjectReference causes nccs to crash

### ISSUE THREAD

**Issue by wschae** [neo-project/neo-devpack-dotnet#568]
If the project has a 'project reference' in it, nccs crashes:

```
D:\Sources\neo-devpack-dotnet\src\Neo.Compiler.CSharp\bin\Debug\net5.0>**nccs  D:\Sources\Hello2\Hello2Contract.csproj**
  Determining projects to restore...
  All projects are up-to-date for restore.
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Neo.Compiler.CompilationContext.CompileProject(String csproj, Options options) in D:\Sources\neo-devpack-dotnet\src\Neo.Compiler.CSharp\CompilationContext.cs:line 160
...

```
![image](https://user-images.githubusercontent.com/4300700/114799762-41634700-9d4d-11eb-9154-073e7f6574aa.png)

Since it is looking for the entry "[libraries][name][files]" but there is no [files] entry for "project" type:

![image](https://user-images.githubusercontent.com/4300700/114800074-db2af400-9d4d-11eb-9b5d-d1eda0fa3990.png)

Not sure if this story (e.g., adding project references to smart contract project) is supported or not. At least, we need better error report if not.

**Comment by erikzhang** [comment]
I will create a PR to support ProjectReference. But fsproj is still not supported.

**Comment by erikzhang** [comment]
@wschae Please check #570. I think it should work, but it doesn't. I don't know why.

**Comment by wschae** [comment]
@erikzhang The PR works for me. Can you elaborate what was not working?
