### ISSUE TITLE
nccs sequence point issues

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#574]
Using https://github.com/devhawk/neo-registrar-sample/tree/devhawk/nccs-sequence-points to compare debugging experience between NEON and NCCS.

The sequence points generated by NEON for Register operation are:
``` json
"sequence-points": [
    "291[0]32:9-32:10",
    "292[0]33:13-33:55",
    "300[0]34:13-34:38",
    "313[0]35:13-35:14",
    "314[0]36:17-36:58",
    "348[0]37:17-37:30",
    "355[0]39:13-39:46",
    "371[0]40:13-40:14",
    "372[0]41:17-41:52",
    "400[0]42:17-42:30",
    "407[0]45:13-45:76",
    "423[0]46:13-46:25",
    "430[0]47:9-47:10"
]
```

Sequence points generated by NCCS for Register operation are:
``` json
"sequence-points": [
    "150[0]32:16-32:53",
    "157[0]33:16-33:36",
    "163[0]35:16-35:57",
    "195[0]36:16-36:29",
    "200[0]38:16-38:44",
    "209[0]40:16-40:51",
    "235[0]41:16-41:29",
    "240[0]44:12-44:75",
    "252[0]45:12-45:24"
]
```

NCCS sequence points have the following issues:
* NCCS is producing fewer sequence points than NEON, which leads to a poorer developer experience. For the Register operation, NEON generates 13 sequence points while NCCS only produces 9
* NCCS sequence point column information usually points to an invalid span. For example, the first sequence point of both NEON and NCCS is line 32, however NEON references the span from columns 9-10 while NCCS references columns 16-53. Line 32 of the source only has 9 characters in it (debugger line/column numbers start from 1 not 0).
* NCCS often appears to place the sequence point after the relevant code when it should be before. For example NCCS has a sequence point mapping address 195 to line 36 of the source document, which reads `Runtime.Log("Domain already registered");` However, looking at the generated instructions, the syscall to `Runtime.Log` appears at address 190, which is *before* the sequence point. NEON maps line 36 to address 314, which is the instruction that pushes "Domain already registered" onto the stack.

NCCS instructions (dump generated by [DumpNef](https://github.com/devhawk/DumpNef))
```
163 PUSHDATA1 44-6F-6D-61-69-6E-20-61-6C-72-65-61-64-79-20-72-65-67-69-73-74-65-72-65-64 # as text: "Domain already registered"
190 SYSCALL CF-E7-47-96 # System.Runtime.Log
# Sequence Point: Registrar.cs line 36: "Runtime.Log("Domain already registered");"
195 PUSH0
196 CONVERT 20
198 JMP 3B # pos: 257, offset: 59
```

NEON instructions
```
# Sequence Point: Registrar.cs line 36: "Runtime.Log("Domain already registered");"
314 PUSHDATA1 44-6F-6D-61-69-6E-20-61-6C-72-65-61-64-79-20-72-65-67-69-73-74-65-72-65-64 # as text: "Domain already registered"
341 NOP
342 SYSCALL CF-E7-47-96 # System.Runtime.Log
347 NOP
```

**Comment by erikzhang** [comment]
> NCCS is producing fewer sequence points than NEON, which leads to a poorer developer experience. For the Register operation, NEON generates 13 sequence points while NCCS only produces 9

That is because the `NOP` instructions are optimized.

**Comment by devhawk** [comment]
> That is because the `NOP` instructions are optimized.

If NoOptimize is specified, will these extra sequence points be left in?

**Comment by erikzhang** [comment]
> If NoOptimize is specified, will these extra sequence points be left in?

Yes.
