### ISSUE TITLE
nccs should emit a sequence point + nop for closing bracket of block

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#589]
Provides developers a mechanism to view local method state before method exits

**Comment by erikzhang** [comment]
There are sequence points for closing bracket of block. But the optimizer will remove all the `NOP`s. To keep them, you need to use `--no-optimize`.

**Comment by devhawk** [comment]
Yup, my bad. It appears to be an issue with sequence points in methods with a return statement and/or expression block statements. I'll close this bug and open a new one after I investigate the problem further.

**Comment by devhawk** [comment]
Opened #590 for the return statement sequence point issue. Still investigating expression block methods

**Comment by devhawk** [comment]
There also appears to be an issue with expression block sequence points, but it may be a debugger issue so I'll need to investigate more.
