### ISSUE TITLE
nccs doesn't report warning/error location

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#599]
Attempting to compile https://github.com/ngdenterprise/neo-fungible-token-sample with nccs, and I get the following output:

``` 
$ dotnet nccs .\src\Apoc.csproj
  Determining projects to restore...
  All projects are up-to-date for restore.
error NC1002: Unknown method: Neo.SmartContract.Framework.SmartContract.Hash160(Neo.SmartContract.Framework.ByteString)
Compilation failed.
```

I'm pretty sure the error is on this line, but nccs should automatically emit line/column info when it encouters code it can't compile

``` csharp
        static readonly UInt160 Owner = "NcH2sq3SABdHYnvBUoPxv5ETQ7B5bTDEQ9".ToScriptHash();
```

**Comment by shargon** [comment]
They must use

```
[InitialValue("NcH2sq3SABdHYnvBUoPxv5ETQ7B5bTDEQ9", ContractParameterType.Hash160)]
private static readonly byte[] Owner = default;
```

**Comment by devhawk** [comment]
I knew that @shargon, but `nccs` should still report the file/line where the problem is located

**Comment by shargon** [comment]
> dotnet nccs .\src\Apoc.csproj

It works for me if we remove the only one smart contract condition 

```csharp
if (scTypeFound) throw new CompilationException(DiagnosticId.MultiplyContracts, $"Only one smart contract is allowed.");
```

**Comment by devhawk** [comment]
@shargon you already [pointed out the solution](https://github.com/neo-project/neo-devpack-dotnet/issues/599#issuecomment-831732795) and I've already [fixed the sample](https://github.com/ngdenterprise/neo-fungible-token-sample/blob/master/src/Apoc.cs#L26).

**Comment by erikzhang** [comment]
It should have been fixed.
