### ISSUE TITLE
Nccs needs option to specify the .nef filename 

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#602]
`nccs` uses the [contract name](https://github.com/neo-project/neo-devpack-dotnet/blob/master/src/Neo.Compiler.CSharp/Program.cs#L111) as the filename for the generated .nef/.manifest.json/.nefdbgnfo files. There is no way for the build system to know the contract name without parsing the contents of the contract source. 

`nccs` should have an option for specifying the base file name used for generated files explicitly.

**Comment by erikzhang** [comment]
How about using the `AssemblyName`?

**Comment by devhawk** [comment]
Sure, `AssemblyName` MSBuild property would be fine.
