### ISSUE TITLE
nccs generating invalid sequence points

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#604]
Test Contract: https://gist.github.com/devhawk/6d9ba02ae26a7f7618f83087c631fc41
Compiled with `dotnet nccs --debug --no-optimize TestContract.csproj`

In the generated debug info, we get sequence points that have an invalid document index of -1

> Note, this may not be a valid contract. As per #603, nccs fails to compile this contract when compiling the .cs file directly instead of compiling the contract via its .csproj file.

``` json
{
    "id": "Neo.SmartContract.Framework.Services.StorageMap.Put\u003CNeo.UInt160\u003E(Neo.SmartContract.Framework.ByteString, Neo.UInt160)",
    "name": "Neo.SmartContract.Framework.Services.StorageMap,Put",
    "range": "268-292",
    "params": [
        "key,ByteArray",
        "value,Hash160"
    ],
    "return": "Void",
    "variables": [],
    "sequence-points": [
        "271[-1]201:9-201:10",
        "272[-1]202:13-202:47",
        "292[-1]203:9-203:10"
    ]
}
```

**Comment by devhawk** [comment]
This appears to happen when the StorageMap.Put<T>method is called

**Comment by erikzhang** [comment]
I think it is caused by #603, which is as expected.

**Comment by devhawk** [comment]
> I think it is caused by #603, which is as expected.

the value in the brackets in an index into the documents array, so negative values don't make any sense.

**Comment by erikzhang** [comment]
I got it. Please check #627

**Comment by devhawk** [comment]
https://discord.com/channels/382937847893590016/382938783563382784/846028896277102653
