### ISSUE TITLE
dotnet new templates should be in this repo

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#609]
there are neo contract templates that work with `dotnet new` in the https://github.com/neo-ngd/Neo3.SmartContract.Templates repo. We should keep the various templates together in one repo.

Also, VS2019 16.8 and later supports `dotnet new` templates directly. We should consider eliminating the VS2019 templates in favor of `dotnet new` templates that work with both VS2019 and command line developers alike

**Comment by erikzhang** [comment]
> Also, VS2019 16.8 and later supports dotnet new templates directly.

Is there any document about this?
