### ISSUE TITLE
nccs non-optimized builds need to emit separate variable slots for each local variable

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#619]
@devhawk 

https://github.com/neo-project/neo-devpack-dotnet/pull/612/files#diff-27038bb15e8236627041207a01a839e1d9fe48fe6c7055371fd2cffc837d4df5R321

`variables` are not arranged according to the index of the slot too. Because different variables may share the same index.

For example:

```c#
void Test(bool flag)
{
    if (flag)
    {
        int i1 = 1;
        //Do something
    }
    else
    {
        int i2 = 2;
        //Else
    }
}
```

Both the variables `i1` and `i2` use the slot index `0`.

_Originally posted by @erikzhang in https://github.com/neo-project/neo-devpack-dotnet/issues/612#issuecomment-840324453_

**Comment by erikzhang** [comment]
> nccs non-optimized builds need to emit separate variable slots for each local variable

If so, the debug info of optimized builds are not usable. I think maybe we should explicitly indicate the slot index used by the variables in the debug information.

**Comment by erikzhang** [comment]
For example:

```json
{ "variables": ["i1,Integer,0", "i2,Integer,0"] }
```

**Comment by devhawk** [comment]
> If so, the debug info of optimized builds are not usable. I think maybe we should explicitly indicate the slot index used by the variables in the debug information.

Optimized/release builds are rarely debuggable in any environment. As long as non-optimized builds are debuggable, we should be fine.

> For example:
> 
> ```json
> { "variables": ["i1,Integer,0", "i2,Integer,0"] }
> ```

This is not sufficient information for the debugger. In addition to knowing there are two variables in a single slot, the deubgger would also need a mechanism to know which variable is valid at any given time.

**Comment by erikzhang** [comment]
Then we shouldn't create the debug info in optimized builds.

**Comment by erikzhang** [comment]
And there are some anonymous variables.

```c#
foreach (var item in collectionExpr)
{
}
```

The value of the `collectionExpr` is stored in an anonymous variable, and it uses a slot.

**Comment by devhawk** [comment]
> Then we shouldn't create the debug info in optimized builds.

I'm more worried about the debug experience on non-optimized builds. For optimized builds, we can investigate adding optional slot info to variables as you proposed.

**Comment by devhawk** [comment]
> The value of the `collectionExpr` is stored in an anonymous variable, and it uses a slot.

If it uses a slot and isn't listed in the variables array, it throws off variable binding for every variable in the array after the missing one. If there are one or more anonymous slots are at the end of the slots, I don't think it's a big deal if they aren't listed in the variables array.

Note, you can inspect method arguments, local variables and static fields using a special hashtag prefixed syntax that's primarily exposed in the disassembler - #arg0, #local1, #static2 - but are available in the evaluation window regardless of debugger mode (source vs. disassembler).
