### ISSUE TITLE
Const or Readonly

### ISSUE THREAD

**Issue by RichardBelsum** [neo-project/neo-devpack-dotnet#621]
https://github.com/neo-project/neo-devpack-dotnet/blob/4e651eccb4ee808d747062a348ea00fe94dbfbd2/src/Neo.SmartContract.Template/templates/neocontract/Contract1.cs#L16-L18

`Const` is assigned at compile time, and `Readonly` is assigned at runtime, so should we use `Const` to save on fees?

**Comment by erikzhang** [comment]
`InitialValue` doesn't support `const`.
