### ISSUE TITLE
Publish Neo.SmartContract.Template to NuGet

### ISSUE THREAD

**Issue by RichardBelsum** [neo-project/neo-devpack-dotnet#623]
How to use `Neo.SmartContract.Template`  to create a project?

Should you publish `Neo.SmartContract.Template` to NuGet and then use `dotnet new -i Neo.SmartContract.Template` to create a new project?

**Comment by RichardBelsum** [comment]
This project is cool, no compiler installation and no environment variable configuration. You can refer to it. 

https://github.com/neo-ngd/Neo3.SmartContract.Templates

**Comment by devhawk** [comment]
I agree we should publish the [smart contract template from this repo](https://github.com/neo-project/neo-devpack-dotnet/tree/master/src/Neo.SmartContract.Template) on nuget for use with `dotnet new`

@ngdenterprise published templates for Neo Legacy (https://github.com/ngdenterprise/neo-templates) but we don't have any for N3

**Comment by chenzhitong** [comment]
I see it has been published on June 3.

https://www.nuget.org/packages/Neo.SmartContract.Template/3.0.0-rc3
