### ISSUE TITLE
nccs mixing implicit and explicit slot index in debug info

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#637]
You can't mix and match implicit and explicit slot indexes in debug info. Either all the variables in a given array must all be implicitly or explicitly indexed.

Example from the registrar sample:

``` json
{
    "id": "DevHawk.Contracts.DomainStorage.DomainStorage(string)",
    "name": "DevHawk.Contracts.DomainStorage,.ctor",
    "range": "212-230",
    "params": [
        "this,Any", // this param has no slot info
        "prefix,String,0" // this param has slot info
    ],
    "return": "Void",
    "variables": [],
    "sequence-points": [
        "215[0]114:9-114:10",
        "216[0]115:13-115:73",
        "230[0]116:9-116:10"
    ]
},
```

**Comment by shargon** [comment]
use -1 if there are no slot index? @devhawk

**Comment by devhawk** [comment]
-1 is not a valid slot index, so please don't do that. 

When using explicit slot indexes, simply omit values that don't have valid slot indexes
