### ISSUE TITLE
Shouldn't mix static and instance methods in TokenContract and subclasses

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#642]
`TokenContract` defines abstract instance methods `Symbol` and `Decimals`, but the other methods like `TotalSupply`, `BalanceOf` as well as subclass methods such as `Transfer` and `OwnerOf` are static. It seems odd from a C# semantics perspective to mix and match like this

**Comment by erikzhang** [comment]
`Symbol` and `Decimals` must be instance methods because they are abstract. The others are static because static methods are cheaper.
