### ISSUE TITLE
Is Nep11Token TokensOf method returning the right value?

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#644]
From NEP-11: `tokensOf` method "Returns an iterator that contains all of the token ids owned by the specified address"

The SmartContract Framework [Nep11Token class](https://github.com/neo-project/neo-devpack-dotnet/blob/master/src/Neo.SmartContract.Framework/Nep11Token.cs#L51) implements tokensOf like this:

``` csharp
 public static Iterator TokensOf(UInt160 owner)
{
    if (owner is null || !owner.IsValid)
        throw new Exception("The argument \"owner\" is invalid");
    StorageMap accountMap = new(Storage.CurrentContext, Prefix_AccountToken);
    return accountMap.Find(owner, FindOptions.KeysOnly | FindOptions.RemovePrefix);
}
```

The problem here is that the key of the Prefix_AccountToken StorageMap is not the token id, but rather the owner and token ID concatenated. You can see where the AccountToken map key is set in `UpdateBalance`

``` csharp
private static void UpdateBalance(UInt160 owner, ByteString tokenId, int increment)
{
    UpdateBalance(owner, increment);
    StorageMap accountMap = new(Storage.CurrentContext, Prefix_AccountToken);
    ByteString key = owner + tokenId;
    if (increment > 0)
        accountMap.Put(key, 0);
    else
        accountMap.Delete(key);
}
```

**Comment by devhawk** [comment]
Note, I think UpdateBalance should be storing the tokenId as the value in the accountMap and TokensOf should be using FindOptions.ValuesOnly

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/0df7f5a7bd7171487c906792373d0d5fb37af3e8/src/neo/SmartContract/Iterators/StorageIterator.cs#L37-L38

The `owner` is removed from the key.

**Comment by devhawk** [comment]
Having `prefix` as both a field and param name is confusing
