### ISSUE TITLE
Nep11API class for RpcClient

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#652]
RpcClient supports the NEP17 standard. It should also support the NEP11 standard. In particular, it should support parsing the iterator values returned from methods like `tokens` and `tokensOf`

See #647 for more details

**Comment by shargon** [comment]
Require https://github.com/neo-project/neo-modules/issues/629

**Comment by erikzhang** [comment]
This should be opened in neo-modules repo.
