### ISSUE TITLE
nccs should not map "<string> += <string>" statement to OpCode.ADD

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#661]
C# developers are used to concatenating strings with the `+=` operator. However, `nccs` maps these operations to OpCode.ADD NeoVM instruction, regardless of the expression type. 

`nccs` should either emit code to concatenate strings when the developer uses the `+=` operator or emit an error that concatenating strings this way is not supported in smart contracts

**Comment by shargon** [comment]
@devhawk do you think that it's solved with https://github.com/neo-project/neo-devpack-dotnet/pull/656 ?

**Comment by devhawk** [comment]
In RC3, I *think* the string add operator support is handled at the compiler level by [TryProcessSystemOperators](https://github.com/neo-project/neo-devpack-dotnet/blob/v3.0.0-rc3/src/Neo.Compiler.CSharp/MethodConvert.cs#L4241). Not sure you can (or should) add add/assignment operator support in the library. We should be consistent about where operator support is implemented.
