### ISSUE TITLE
UInt160/bytestring tostring method

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-devpack-dotnet#666]
Sometimes we need to throw exceptions about the bytestring, and they can not be shown in string format.

**Comment by cloud8little** [comment]
Though UInt160 tostring is resolved in https://github.com/neo-project/neo-devpack-dotnet/pull/665 , when bytestring length is not 20 bytes, it still can not be converted to string.

**Comment by erikzhang** [comment]
you can use `StdLib.Base64Encode()` method.
