### ISSUE TITLE
DisplayName attribute of Class is not available

### ISSUE THREAD

**Issue by RichardBelsum** [neo-project/neo-devpack-dotnet#674]
DisplayName attribute of Class is not available, by design?

```c#
namespace ContractA
{
    [DisplayName("ContractB")]
    public class ContractA : SmartContract
    {

    }
}
```

**Comment by shargon** [comment]
I tested it, and it works... :S

**Comment by RichardBelsum** [comment]
I'm using nccs 3.0.2 version, was it fixed after that?

![image](https://user-images.githubusercontent.com/82148280/130716489-aa7e1568-2aa0-43cf-b6ed-a8e70d0fcb46.png)

**Comment by cloud8little** [comment]
In https://github.com/neo-project/neo-devpack-dotnet/pull/607/files, the first priority is assembly name, use --contract-name xx to change the manifest name.
