### ISSUE TITLE
FEATURE: Add ToString() method to UInt160 type.

### ISSUE THREAD

**Issue by roschler** [neo-project/neo-devpack-dotnet#676]
Currently, to convert a `UInt160` value to a string you can use with facilities like `Runtime.Log()`, you have to do this bit of trickery (thank you @Hal0x2328):
```
StdLib.Base58CheckEncode("5" + (ByteString) value))
```
Where `value` is a `UInt1601 value.  I suggest making a `ToString()` method for the `UInt160` type so that it is easily discoverable by NEO developers.

**Comment by erikzhang** [comment]
Now you can use `UInt160.ToAddress()` method.
