### ISSUE TITLE
C# plug-in and contract compiler does not flag use of the "dynamic" keyword.

### ISSUE THREAD

**Issue by roschler** [neo-project/neo-devpack-dotnet#683]
The NEO N3 C# compiler does not issue any warnings when compiling code that contains use of the C# `dynamic` keyword.  The editor plug-in does not highlight it as an error either.  My understanding is that the `dynamic` keyword is unsupported.

**Comment by shargon** [comment]
Could you send us an example, I receive an error:

```./TestClasses/Contract_Dynamic.cs(5,39): error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?```

**Comment by erikzhang** [comment]
If you use dynamic on the return type, to the compiler, it is equivalent to returning an object.
