### ISSUE TITLE
To remove duplicating entries of methods in `.manifest.json` when inheritance and override is specified in C# contract

### ISSUE THREAD

**Issue by Hecate2** [neo-project/neo-devpack-dotnet#686]
If inheritance and override is specified in a C# contract like this,
```C#
public class MyContract : Nep17Token
// Nep17Token has a `Transfer` method which would be overriden in MyContract
{
    public static new bool Transfer(UInt160 from, UInt160 to, BigInteger amount, object data) {... ....}
}
```
then NCCS would put two `transfer` json entries in `.manifest.json`. If a user deploys the `.nef` file with the `.manifest.json` using neo-cli, there can be a confusing error like this:
```
Error: An item with the same key has already been added. Key: (transfer, 4)
```  
As an example to reproduce the problem, you may compile https://github.com/neoburger/code/blob/main/BurgerNEO.cs. Please remember to replace `[TODO]: ARGS` in the contract with any N3 wallet address (e.g. `Nb2CHYY5wTh2ac58mTue5S3wpG6bQv5hSY`) before compiling. 
  
It is still possible to deploy the compiled contract simply by deleting the first `transfer` entry in `.manifest.json`. That is to remove a whole piece of text like this:
```
{"name":"transfer","offset":409,"safe":false,"returntype":"Boolean","parameters":[{"name":"from","type":"Hash160"},{"name":"to","type":"Hash160"},{"name":"amount","type":"Integer"},{"name":"data","type":"Any"}]},
```  
But it might be a better way to filter the variable `List<AbiMethod> methodsExported` in `neo-devpack-dotnet\src\Neo.Compiler.CSharp\CompilationContext.cs`, removing methods of duplicate names before dumping the variable to a json file. Maybe we can have even better solutions implemented deep in the compiler.

**Comment by shargon** [comment]
I will take a look

**Comment by erikzhang** [comment]
I'm not sure in which PR it was fixed, but it should have been fixed.
