### ISSUE TITLE
NEO GUI autogenerated abi can have different case than functions in CSharp

### ISSUE THREAD

**Issue by roadbuilder** [neo-project/neo-devpack-dotnet#690]
I noticed that in C# the functions names are case-sensitive, but in the N3 GUI, the "abi" for the manifest file changes the first letter of the function name to lower case.. but only the first letter! 
![image](https://user-images.githubusercontent.com/74831504/139560331-d897ec04-0143-46ee-b552-06f98b573c8c.png)
MINTTHISTHING has become mINTTHISTHING, and the MintThisThing now is a duplicate as it is now mintThisThing
![image](https://user-images.githubusercontent.com/74831504/139560340-c951b878-e4cd-4ec4-96c9-b592676bb39d.png)

I found a work-around in case it is needed but if the DisplayName is put in front of each function, then the case isn't changed in the ABI function names:
![image](https://user-images.githubusercontent.com/74831504/139560350-67cc6a26-10d3-4fc4-b505-76dc8d5dc64a.png)
Result:
![image](https://user-images.githubusercontent.com/74831504/139560359-cd60cd83-4b8d-45dc-82d1-99aee7777f07.png)

**Comment by erikzhang** [comment]
If you use `DisplayNameAttribute`, the first letter will not be changed. This is by design on purpose. This way you have full control over its name.
