### ISSUE TITLE
Contract can not reference an extension outside its namespace

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-devpack-dotnet#691]
For example, there is a common extension library which Contract A and Contract B both need. Currently the only way is to copy all the extension files to the contract project namespace.

**Comment by erikzhang** [comment]
You can reference a library only if it contains source code. You can refer to the packaging method of Neo.SmartContract.Framework.

https://github.com/neo-project/neo-devpack-dotnet/blob/815c17f457783387da1cebbe6dcfbacd23961a7a/src/Neo.SmartContract.Framework/Neo.SmartContract.Framework.csproj#L16-L19

**Comment by shargon** [comment]
> You can reference a library only if it contains source code.

A nuget with the source code will work?

**Comment by erikzhang** [comment]
> A nuget with the source code will work?

Yes.
