### ISSUE TITLE
Suggestion: Copy the transaction result line to the TOP of the Visual Dev Tracker data inspector result?

### ISSUE THREAD

**Issue by roschler** [neo-project/neo-devpack-dotnet#699]
(moved to Visual Dev Track repo.  Please delete this issue.)

**Comment by Liaojinghui** [comment]
This issue might be moved to another repo.

**Comment by roschler** [comment]
@Liaojinghui Thanks.  Already moved to the Visual Dev Tracker repo as per Edge's suggestion on the discord.
