### ISSUE TITLE
Implement cross platform compatibility - Visual Studio for Mac

### ISSUE THREAD

**Issue by rywem** [neo-project/neo-devpack-dotnet#7]
Implement fixes and changes to enable cross platform compatibility with Visual Studio for Mac.

**Comment by joeblau** [comment]
I'm looking into how to get this to work for Visual Studio on a Mac as well.

**Comment by lock9** [comment]
I did a template in #79  if you guys want to check.

**Comment by shargon** [comment]
Is not compatible with mac right now?

**Comment by lock9** [comment]
It works fine now. I will close this. Thanks.
