### ISSUE TITLE
NCCS doesn't support new C# 10 syntax for namespaces

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#711]
This is valid C# as of net6.0, but nccs doesn't support it:

``` csharp
using Neo.SmartContract.Framework;

namespace MyContractNamespace; // namespace statement is new in C# 10

public class MyContract : SmartContract
{
  // contract contents omitted
}
```

**Comment by Liaojinghui** [comment]
LOL, i thought you reopened my issue. https://github.com/neo-project/neo-devpack-dotnet/issues/702

**Comment by devhawk** [comment]
> LOL, i thought you reopened my issue. #702

Sorry, I should have searched for an existing issue - though I wouldn't have searched closed issues.
