### ISSUE TITLE
Floating-point math support

### ISSUE THREAD

**Issue by ediopia** [neo-project/neo-devpack-dotnet#715]
I have to calculate ownership percentage for my defi contracts.
The current issue is VM cannot calculate float point.
Ex. (10 / 100 ) * 100 return 0
If dividend is smaller than divisor, it always returns 0 so I need to use my hack to calculate it.
It will be much easier we have a util for this.

**Comment by Liaojinghui** [comment]
(10*100,000,000 /100)*100

**Comment by erikzhang** [comment]
Using floating point numbers in a blockchain is dangerous. Fixed-point numbers should be used.
