### ISSUE TITLE
Rescope methods marked as "private protected" as "protected

### ISSUE THREAD

**Issue by roschler** [neo-project/neo-devpack-dotnet#717]
There are several methods marked as "private protected in the `TokenContract.cs` module (e.g. - `UpdateTotalSupply`, etc.).  Please redeclare these functions as simply "protected".  Currently they can not be used outside the assembly they reside in.  The scope declarations as is makes proper integration and debugging of that contract code awkward and unfriendly.

**Comment by shargon** [comment]
Related to https://github.com/neo-project/neo-devpack-dotnet/pull/654
