### ISSUE TITLE
Nep11Token Transfer method should thrown an exception if CheckWitness fails

### ISSUE THREAD

**Issue by roschler** [neo-project/neo-devpack-dotnet#718]
In the current implementation of `Nep11Token.cs` in the `Transfer()` method, that method returns FALSE if the `CheckWitness()` call fails.  This can lead to a silent failure if it occurs in an unexpected place.  Given that proper scoping and permissions is a complex, error prone field, please change the code in this method to throw an exception so that devs are immediately aware of the problem.

**Comment by erikzhang** [comment]
https://github.com/neo-project/proposals/blob/master/nep-11.mediawiki#transfer

The NEP-11 standard states that `false` should be returned in this case.
