### ISSUE TITLE
call for v3.2.1 native contract's method support

### ISSUE THREAD

**Issue by dusmart** [neo-project/neo-devpack-dotnet#729]
CryptoLib add a method called murmur128 which could help us a lot. Please add it to devpack.

**Comment by Liaojinghui** [comment]
Its a native contract method, just call it from native contact then CryptoLib.Murmur128

**Comment by Liaojinghui** [comment]
Its murmur32, cause we already have sha256 and RIPEMD160，，，，adding murmur32 makes more sense.
