### ISSUE TITLE
Re-entrancy support for contracts with instance method operations 

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#732]
NCCS introduced the ability to expose instance methods as operations, such as in this example code:

``` csharp
public class KVStore : SmartContract
{
    public KVStore() { /* constructor logic omitted */ }

    [Safe]
    public string Read(string key) { /* read logic omitted */ }

    public void Write(string key, string value) { /* write logic omitted */ }
}
```

For public instance methods, NCCS will construct a [method forward](https://github.com/neo-project/neo-devpack-dotnet/blob/master/src/Neo.Compiler.CSharp/MethodConvert.cs#L195-L205) that constructs an instance of the contract object and then jumps to the instance method that represents the operation. Conceptually, it would look something (but not exactly like) this in C#:

> Note, `$` character is not a valid C# identifier character, so it's used in this code snippet to indicate compiler generated or transformed identifiers

``` csharp
public class KVStore : SmartContract
{
    public KVStore() { /* constructor logic omitted */ }

    [Safe]
    string $Read(string key) { /* read logic omitted */ }

    public static Read(string key) {
        var contract = new KVStore();
        return contract.$Read(key);
    }

    void $Write(string key, string value) { /* write logic omitted */ }

    public static Write(string key, string value) {
        var contract = new KVStore();
        contract.$Write(key, value);
    }
}
```

This approach works so long unless the contract has instance variables and supports re-entrancy. If an instance method contract calls into an external contract which in turns calls back into an instance method of the original contract, the associated method forward would create a new contract instance with new instance variables.

I think a C# contract developer would expect a re-entrant call would use the same contract instance and that the contract instance fields would be the same for both the original call and the re-entrant call. I.e. if the original call sets a instance field to a specific value, the developer would expect the re-entrant call to see that value.

To resolve this, I propose using a static contract field to store a single instance of the contract. The initial operation invocation would initialize this static field to a new instance of the contract. Re-entrant calls to the contract would use the already-initialized instance rather than creating a new once. The logic would look something like this in C#:

``` csharp
public class KVStore : SmartContract
{
    static KVStore $instance = null;

    public KVStore() { /* constructor logic omitted */ }

    [Safe]
    string $Read(string key) { /* read logic omitted */ }

    public static Read(string key) {
        if ($instance is null) $instance = new KVStore();
        return $instance.$Read(key);
    }

    void $Write(string key, string value) { /* write logic omitted */ }

    public static Write(string key, string value) {
        if ($instance is null) $instance = new KVStore();
        $instance.$Write(key, value);
    }
}
```

**Comment by erikzhang** [comment]
In this case even a static variable cannot hold its value. Because when an external contract calls this contract, a new `ExecutionContext` is created.

**Comment by erikzhang** [comment]
To maintain state across callbacks, the current practice is to add a state parameter to the methods. For example, the `transfer` method of NEP-17 and the `onNEP17Payment` method.

```c#
public bool transfer(UInt160 from, UInt160 to, BigInteger amount, object data);
public void onNEP17Payment(UInt160 from, BigInteger amount, object data);
```

In the above example, the `data` parameter is used to maintain state.
