### ISSUE TITLE
Unable to Deserialize JSON

### ISSUE THREAD

**Issue by robbhudl** [neo-project/neo-devpack-dotnet#752]
I'm serializing an object to a JSON string so that I can store it in a StorageMap. The serialize call works fine.

However, if I add the following code
```
var result = System.Text.Json.JsonSerializer.Deserialize<Result>(obj);
```

I get a compiler error

NC1002	Unknown method: System.Text.Json.JsonSerializer.Deserialize<LeagueResults.Result>(string, System.Text.Json.JsonSerializerOptions?)

**Comment by shargon** [comment]
You must call [StdLib.JsonDeserialize](https://github.com/neo-project/neo-devpack-dotnet/blob/c7b89cd175ca73b5636b5903587e835cfc934fb7/src/Neo.SmartContract.Framework/Native/StdLib.cs#L30)

**Comment by robbhudl** [comment]
Amazing, thanks!
