### ISSUE TITLE
Incorret NEP17 example

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-devpack-dotnet#780]
Hi, 
The NEP-17 example is incorrect and will likely break (unless it was updated recently):
https://github.com/neo-project/neo-devpack-dotnet/blob/master/src/Neo.SmartContract.Framework/Nep17Token.cs

The following lines won't work:
```C#
protected static void PostTransfer(UInt160 from, UInt160 to, BigInteger amount, object data)
        {
            OnTransfer(from, to, amount);
            if (to is not null && ContractManagement.GetContract(to) is not null)
                Contract.Call(to, "onNEP17Payment", CallFlags.All, from, amount, data);
        }
```

We need to revert the hex before calling the GetContract and Contract.Call.

Is there any chance we can remove the need for reverting hex when invoking / calling other contracts? I don't even know how to document this. What's the justification? Can someone help me explain this requirement to a new developer?

**Comment by Liaojinghui** [comment]
I am quite confused by your question, this has been adopted by many projects, I don't see any issue here. May I ask why would you need to revert the hex? Is that possible to provide more context?

**Comment by lock9** [comment]
When calling external contracts, we had to revert the scripthash before using Contract.Call. At least this was happening in my local contract with Neo Express.  The opcode itself expects a reversed hex, but the compiler may auto revert it.
I'm testing the same contract in different programming language, maybe the compiler that I'm using is not converting it

**Comment by roman-khimov** [comment]
The example is correct, it's just neo-project/neo#938 and it can't be fixed now.

**Comment by Liaojinghui** [comment]
> The example is correct, it's just [neo-project/neo#938](https://github.com/neo-project/neo/issues/938) and it can't be fixed now.

I am always impressed by how many issues you can refer to, even dating back many years ago.

**Comment by lock9** [comment]
> I've had dreams about a NEO4 where we deleted the `reverse()` call, removed the `0x` prefix and just called it `Hash160/256` (to nicely align with the ABI parameter names), it was amazing 😄 . This to me has always felt like NEOs equivalent of Tony Hoare's [null reference mistake](https://en.wikipedia.org/wiki/Tony_Hoare#cite_note-26).

Haha. I have similar dreams 😂 

Guys, I'm still confused. When should we use big endian or little endian?  

Example:
```
PUSHINT64 c800ad4787010000
PUSHDATA1 20f0bea450ada7b903b89749d7c9bbc160b148cd
PUSHDATA1 b15f3a93f9e33b279ef052736ba5c2bc00d40510
PUSHDATA1 2a4c9a4d4022678b03ef1bbe0834f966460dc448
PUSH3
PACK
PUSH0
PUSHINT64 8a6a109001000000
PUSHDATA1 b177cb216f8d1872f98eb36824e975726d1ff0c2
PUSH5
PACK
PUSH15
PUSHDATA1 73776170546f6b656e496e466f72546f6b656e4f7574
PUSHDATA1 234fd7258cc35d7721b83237b665d7ecccf470f9
SYSCALL System.Contract.Call
```

This: `234fd7258cc35d7721b83237b665d7ecccf470f9` must be reversed into this: `f970f4ccecd765b63732b821775dc38c25d74f23` (flamingo swap router)

![Screenshot 2023-04-03 at 12 14 32](https://user-images.githubusercontent.com/38396062/229552801-6fa20e1d-7d65-45f2-a33a-022a78176fdf.png)


![Screenshot 2023-04-03 at 12 13 52](https://user-images.githubusercontent.com/38396062/229552586-454a270c-487c-4aae-9191-ea56811dfd7d.png)


I know I've created this issue, but I have no idea what is happening. Who and when should we reverse bytes? Is this done at the compiler level?

**Comment by ixje** [comment]
> I know I've created this issue, but I have no idea what is happening. Who and when should reverse bytes? Is this done at the compiler level?

It is done by whichever tool creates the script. For example if you'd use `neo-mamba` then it is your responsibility to call `UInt160.from_string("0x<some_script_hash_string>")` or `UInt160(<script_hash_bytes>)`. The former will internally reverse the data, the latter won't.

**Comment by lock9** [comment]
In this case, this won't work, right? (pseudocode)

```
var my_account = UInt160(<hash>)
var contract_hash = UIn160(<hash>)
transfer(my_account, contract_hash, 100)
contract.call(contract_hash, "onNEP17Payment", my_account, 100, [])
```

Should I do something like this instead:

```
var my_account = UInt160(<hash>)
var contract_hash = UIn160(<hash>)
transfer(my_account, contract_hash, 100)
contract.call(""+contract_hash, "onNEP17Payment", my_account, 100, [])
```

?

The problem is that, at least in some SDKs, serialization is not reversing the hex. As you pointed out, you get different results depending on how you write it. Is there a rule that we can use to avoid such issues?

**Comment by lock9** [comment]
Hello. Just did a few more tests here. Something is weird and I don't even know how to explain properly.
Take a look at this:
![Screenshot 2023-04-03 at 14 19 25](https://user-images.githubusercontent.com/38396062/229581684-2f1918ae-dc35-481f-b0d1-e9813ec92dda.png)

As we can see, we have a contract called Token2, with the following script hash:
`0x5b397d3664107f8c552002ec3dcc62991251a972`

I can invoke it using NeoExpress:
```
neoxp contract run  0x5b397d3664107f8c552002ec3dcc62991251a972 onNEP17Payment 0x00 0x00 0  -r
VM State:     HALT
Gas Consumed: 1047480
Result Stack:
  <null>
```

However, if I use the ContractManagement, it doesn't find it as is:

```
neoxp contract run ContractManagement getContract 0x5b397d3664107f8c552002ec3dcc62991251a972  -r
VM State:     HALT
Gas Consumed: 2028330
Result Stack:
  <null>
```


However, if I revert the hex, it does find the contract:

```
neoxp contract run ContractManagement getContract 0x72a951129962cc3dec0220558c7f1064367d395b -r
VM State:     HALT
Gas Consumed: 2028330
Result Stack:
  Array: (5)
    2
    0
    72a951129962cc3dec0220558c7f1064367d395b
    4e4546336e656f332d626f6120627920434f5a2d302e31322e3100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000557000321408a0aaacc
    Array: (8)
      746f6b656e32
      Array: (0)
      Map: (0)
      Array: (0)
      Array: (2)
        Array: (1)
          Array: (5)
            6f6e4e455031375061796d656e74
            Array: (3)
              Array: (2)
                66726f6d5f706172616d
                20
              Array: (2)
                616d6f756e74
                17
              Array: (2)
                64617461
                0
            255
            0
            false
        Array: (0)
      Array: (1)
        Array: (2)
          <null>
          <null>
      Array: (0)
      6e756c6c
```

I don't know if this is my fault or if this is something with Neo express. Can someone help me?

**Comment by lock9** [comment]
Thanks @ixje. I don't know if I close this and open another issue inside Neo Express. I'm going to leave this here for a few more hours or days, and if it's 100% certain it's a neo express issue, I'll create it there

**Comment by ixje** [comment]
> These contract arguments are string encoded values, following similar rules to [string arguments in an invocation file](https://github.com/ngdenterprise/design-notes/blob/master/NDX-DN12%20-%20Neo%20Express%20Invoke%20Files.md#args-property).

Have you tried encoding the argument? I tried some variations of the below but couldn't get it to work. Maybe you can
```
neoxp contract run -r ContractManagement getContract {"type":"Hash160","value":"7f513a2129dd800e1db8c2a57bc0873a021c9b7f"} 
```

**Comment by ixje** [comment]
@devhawk can probably enlighten us with the correct syntax

**Comment by lock9** [comment]
> From the docs
> 
> > These contract arguments are string encoded values, following similar rules to [string arguments in an invocation file](https://github.com/ngdenterprise/design-notes/blob/master/NDX-DN12%20-%20Neo%20Express%20Invoke%20Files.md#args-property).
> 
> Have you tried encoding the argument? I tried some variations of the below but couldn't get it to work. Maybe you can
> 
> ```
> neoxp contract run -r ContractManagement getContract {"type":"Hash160","value":"7f513a2129dd800e1db8c2a57bc0873a021c9b7f"} 
> ```

```
$ neoxp contract run -r ContractManagement getContract {"type":"Hash160","value":"40e551f7a791743287b0c5f14ad9c80c8e48cbc1"}  
VM State:     FAULT
Gas Consumed: 1045500
Exception:   Method "getContract" with 2 parameter(s) doesn't exist in the contract 0xfffdc93764dbaddd97c48f252a53ea4643faa3fd.
```

Let's wait for @devhawk. I'm probably doing something wrong too

**Comment by lock9** [comment]
> You can prefix a contract parameter with # to force it to be parsed as a hash 160/256.
> 
> Using [NeoToken's hash](https://dora.coz.io/contract/neo3/mainnet/0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5) as an example
> 
> ```shell
> > neoxp contract run ContractManagement getContract 0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5 -r
> VM State:     HALT
> Gas Consumed: 2028330
> Result Stack:
>   <null>
> 
> > neoxp contract run ContractManagement getContract "#0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5" -r
> VM State:     HALT
> Gas Consumed: 2028330
> Result Stack:
>   Array: (5)
>     -5
>     (remaining array contents omitted)
> ```
> 
> > Note, I needed to wrap the contract hash in quotes since the # character starts a comment in bash and powershell

But the problem also happens at the smart contract level, not only when using the command line. Neo express is also capable of finding the contract when we call it using `neoxp contract run`.

This won't work without reverting:

```Python
@public
def transfer(from_param: UInt160, to: UInt160, amount: int, user_data: Any) -> bool:
    # Get the balance of that the transaction is authorized by the sender and that the amount is positive.
    if runtime.check_witness(from_param) and amount > 0:
        # Get the balance of the sender. If the balance is less than the amount being transferred, return False.
        from_balance = balanceOf(from_param)
        if from_balance >= amount:
            # Get the balance of the receiver. If the balance doesn't exist, it is initialized to 0.
            to_balance = balanceOf(to)

            # Update the balances in storage.
            storage.put(from_param, from_balance - amount)
            storage.put(to, to_balance + amount)

            # Notify the blockchain of the transfer event.
            OnTransfer(from_param, to, amount)

            other_contract = contractmanagement.ContractManagement.get_contract(
                to) # The contract is not found if we don't revert the bytes
            if other_contract is not None:
                # Call the onNEP17Payment method of the receiver if it exists.
                if contractmanagement.ContractManagement.has_method(to, "onNEP17Payment", 3):
                    contract.call_contract(to, "onNEP17Payment", [
                        from_param, amount, user_data])

            return True
    return False
```

**Comment by lock9** [comment]
Since this is something with Neo Express, I'm going to close this issue.
