### ISSUE TITLE
Missing `getContractById` and `getContractHashes` native Management APIs

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo-devpack-dotnet#784]
https://github.com/neo-project/neo/pull/2807 introduces `getContractById` and `getContractHashes` methods of native `ContractManagement` contract. This change was included into 3.5.0 and currently is missing from the devpack, we need to add it to https://github.com/neo-project/neo-devpack-dotnet/blob/master/src/Neo.SmartContract.Framework/Native/ContractManagement.cs.

**Comment by Liaojinghui** [comment]
@AnnaShaleva are you working on addressing it?

**Comment by AnnaShaleva** [comment]
> @AnnaShaleva are you working on addressing it?

No, I’ve just created the issue.
