### ISSUE TITLE
Operator `+=` used for ByteString concat instead of BigInteger ADD.

### ISSUE THREAD

**Issue by Hecate2** [neo-project/neo-devpack-dotnet#787]
Assume that we are going to write a smart contract that gets a count of random ByteString bits:
```csharp
        public static ByteString Bits(int count)
        {
            ByteString result = ByteString.Empty;
            for (; count > 128; count -= 128)
                result += (ByteString)Runtime.GetRandom();
            result += (ByteString)(Runtime.GetRandom() >> (128-count));
            return result;
        }
```
The line `result += (ByteString)Runtime.GetRandom();` is compiled like this:
```
# Code RandLib.cs line 39: "result += (ByteString)Runtime.GetRandom();"
184 LDLOC0
185 SYSCALL 6B-DE-A9-28 # System.Runtime.GetRandom SysCall
190 CONVERT 28
192 ADD  # WATCH THIS!
193 DUP
194 STLOC0
195 DROP
```
After `CONVERT 28`, the EvaluationStack shall be like:
```
[
  {'type': 'ByteString', 'value': ''},     # variable `result`
  {'type': 'ByteString', 'value': 'BA=='}  # value of (ByteString)Runtime.GetRandom()
]
```
where `BA==` stands for `4` in base64 bytes. But then `ADD` converts the ByteStrings to BigInteger, because in neo-vm, the OpCode ADD goes like this:
```csharp
                case OpCode.ADD:
                    {
                        var x2 = Pop().GetInteger();
                        var x1 = Pop().GetInteger();
                        Push(x1 + x2);
                        break;
                    }
```
Therefore, the resulting EvaluationStack after `ADD` is:
```
[{'type': 'Integer', 'value': '4'}]
```
Maybe we need to change the OpCodes for which `+` and `+=` are compiled for 2 ByteString operands, or at least notice the users in docs.

**Comment by Hecate2** [comment]
Maybe we do not need to change the assembly codes of the deployed contracts, but just change some lines in our compiler?
https://github.com/neo-project/neo-devpack-dotnet/blob/00bad5cfca1465291e51bf30dfe9479dafd0d259/src/Neo.Compiler.CSharp/MethodConvert.cs#L2003
https://github.com/neo-project/neo-devpack-dotnet/blob/00bad5cfca1465291e51bf30dfe9479dafd0d259/src/Neo.Compiler.CSharp/MethodConvert.cs#L2107

**Comment by shargon** [comment]
It should be a concat, it looks like a failure

**Comment by Liaojinghui** [comment]
Then lets fix it.

**Comment by Hecate2** [comment]
> Then lets fix it. @Hecate2 can you open a PR?

Trying on it
