### ISSUE TITLE
Error NC2001: `Unsupported pattern type: Neo.UInt160`

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-devpack-dotnet#791]
error NC2001: Unsupported pattern type: Neo.UInt160

I keep getting this error and i don't why! One project works and the other doesn't but there all the same but the code.....

See for yourself.
[working.zip](https://github.com/neo-project/neo-devpack-dotnet/files/12567688/working.zip)
[not working.zip](https://github.com/neo-project/neo-devpack-dotnet/files/12567690/not.working.zip)

**Comment by cschuchardt88** [comment]
if you could so kindly tell what is causing the problem with `nccs` in this file [MyNep17Contract.cs](https://github.com/cschuchardt88/neo-examples-csharp/blob/master/src/Nep17ContractExample/MyNep17Contract.cs)

**Comment by cschuchardt88** [comment]
If i try to compile the `cs` file it now give me this error
```
error NC1002: Unknown method: Neo.SmartContract.Framework.TokenContract.TotalSupply()
```

Some help would be appreciate it

**Comment by shargon** [comment]
I only removed 

```csharp
using System.Collections.Generic;
```

and it works for me.

**Comment by cschuchardt88** [comment]
Thanks for the response but i commented out that method  and i dont use `System.Collections.Generic` and i still get the same error. 

`C:\Users\PC1\.nuget\packages\neo.smartcontract.framework/3.5.0\src/UInt160.cs(18,27): error NC2001: Unsupported pattern type: Neo.UInt160`

Here is full error.
```
1>Target PostBuild:
1>  Task "Exec"
1>    nccs "MyNep17Contract.csproj"
1>      Determining projects to restore...
1>      All projects are up-to-date for restore.
1>    C:\Users\Chris\.nuget\packages\neo.smartcontract.framework/3.5.0\src/UInt160.cs(18,27): error NC2001: Unsupported pattern type: Neo.UInt160
1>    Compilation failed.
1>    C:\Users\Chris\Projects\cschuchardt88\neo-examples-csharp\src\Nep17ContractExample\MyNep17Contract.csproj(17,5): error MSB3073: The command "nccs "MyNep17Contract.csproj"" exited with code 1.
1>  Done executing task "Exec" -- FAILED.
1>Done building target "PostBuild" in project "MyNep17Contract.csproj" -- FAILED.
1>Target _CleanRecordFileWrites:
1>  Task "RemoveDuplicates"
1>  Done executing task "RemoveDuplicates".
1>  Task "MakeDir"
1>  Done executing task "MakeDir".
1>  Task "WriteLinesToFile"
1>  Done executing task "WriteLinesToFile".
1>
1>Done building project "MyNep17Contract.csproj" -- FAILED.
1>
1>Build FAILED.
1>
1>C:\Users\Chris\.nuget\packages\neo.smartcontract.framework/3.5.0\src/UInt160.cs(18,27): error NC2001: Unsupported pattern type: Neo.UInt160
1>C:\Users\Chris\Projects\cschuchardt88\neo-examples-csharp\src\Nep17ContractExample\MyNep17Contract.csproj(17,5): error MSB3073: The command "nccs "MyNep17Contract.csproj"" exited with code 1.
1>    0 Warning(s)
1>    2 Error(s)
```

**Comment by vncoelho** [comment]
I tried to look your example and also got an error when you used `as Transaction`.
Then, tried with `((Transaction)Runtime.ScriptContainer).Sender` directly and it failed but without errors.

**Comment by cschuchardt88** [comment]
Thx for the help guys, I don't make smart contracts. But with your guys help I got it working.

You can't use neo types with the `as` keyword? So you can't explicitly convert types?

**Comment by shargon** [comment]
What version of nccs are you using? I'm tried with master branch

**Comment by cschuchardt88** [comment]
3.6.0 and dotnet 6.0, but i did get it working.

had to do 
```csharp
var account = (UInt160)Data
```
VS
```csharp
var account = Data as UInt160
```

**Comment by shargon** [comment]
I really think that this was a bug fixed here https://github.com/neo-project/neo-devpack-dotnet/pull/956/files#diff-db64fc14d8c39d53f7941384edb0046383f113469c63943da01404b2e9a42012R186

The namespace of Uint was changed in this pr, but these types has the wrong previously namespace, it was `Neo`. If the issue remains, please reopen it.
