### ISSUE TITLE
Allowing Unicode in Manifest

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-devpack-dotnet#802]
You allow unicode in manifest. yes you can't do anything with it and doesn't break anything but the VM, only if an contract were to use it in a call. I thought all of neo was UTF8 Strict. Is that the intended way for it to work? Should we allow unicode in manifest? Nep-15 doesn't say we can't...

```csharp
[ManifestExtra("Copyright", "\u00a9 neo.events 2023")]
...
public static ByteString DoRequest()
{
    var contract = ContractManagement.GetContract(Runtime.ExecutingScriptHash);
    if (contract != null)
    {
        var jsonObj = (Map<string, string>)StdLib.JsonDeserialize(contract.Manifest.Extra);
        return jsonObj["Copyright"];
    }
    return null;
}
```

if you don't cast to string it works fine.
 Have a look at 0x4491c87d40cc614fa9de1d08734ba830f37f52b1 on testnet 

```json
"Copyright": "© neo.events 2023"
```

```
Invoking script with: 'wh8MCWRvUmVxdWVzdAwUsVJ/8zCoS3MIHd6pT2HMQH3IkURBYn1bUg=='
...
Result Stack: [{"type":"ByteString","value":"wqkgbmVvLmV2ZW50cyAyMDIz77\u002B9"}]
```

**Comment by cschuchardt88** [comment]
Nevermind i said a bug in the contract, fixed it now. Now you can use json with unicode in a contract.

**Comment by shargon** [comment]
> Nevermind i had a bug in the contract, fixed it now. Now you can use json with unicode in a contract.
