### ISSUE TITLE
nccs 3.6 does not support char to biginteger conversion.

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-devpack-dotnet#810]
```csharp
var typeName = (ByteString)((BigInteger)'A' + secondType);
```

The above code compiles successfully with nccs 3.5 and earlier, but with 3.6 it reports an error

Unknown method: System.Numerics.BigInteger.implicit operator System.Numerics.BigInteger(char)

nccs 3.5.0

<img width="752" alt="image" src="https://github.com/neo-project/neo-devpack-dotnet/assets/6295602/e32ad34d-6958-481e-9d58-76d9f4f5b96f">

nccs 3.6.0

<img width="754" alt="image" src="https://github.com/neo-project/neo-devpack-dotnet/assets/6295602/beff6588-5529-4296-bade-f71d51a7b70e">

**Comment by chenzhitong** [comment]
The errors start after this commit https://github.com/neo-project/neo-devpack-dotnet/commit/c7098b3946a294798130175b70f566a75cfd4f57

**Comment by Liaojinghui** [comment]
I'll check

**Comment by Liaojinghui** [comment]
@chenzhitong  you can use (byte)'A'

**Comment by chenzhitong** [comment]
![image](https://github.com/neo-project/neo-devpack-dotnet/assets/6295602/feeb57f3-fd28-478c-848b-cf8382a59aa2)
@Liaojinghui

**Comment by Liaojinghui** [comment]
(Big)(byte)'',,i mean,,,,kinda dirty

**Comment by cschuchardt88** [comment]
why not just use string?

```csharp
var typeName = (ByteString)("A" + secondType);
```

**Comment by Liaojinghui** [comment]
> why not just use string?
> 
> ```cs
> var typeName = (ByteString)("A" + secondType);
> ```

I think what he want might be "ingeger plus integer".

**Comment by chenzhitong** [comment]
> why not just use string?
> 
> ```cs
> var typeName = (ByteString)("A" + secondType);
> ```

What I want is: input 1, return B, not A1; input 2 return C, not A2
