### ISSUE TITLE
Nep11Token `ownerOf` Invalid Format

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-devpack-dotnet#812]
I'm trying to validate a nep11 token that use `Nep11Token` class. But i get error `One of the identified items was in an invalid format.` for method `ownerOf`. Which has to do with `StdLib.Deserialize` crashing because if the `tokenId` doesn't exist. The `StdLib.Deserialize` is getting `null` passed.

The spec only says `The parameter tokenId SHOULD be a valid NFT ID (64 or less bytes long). If not, this method SHOULD throw an exception.` Which would indicate that something should return. However I don't believe I should be getting this error.

Also `Decimals` is not set to `[Safe]`
https://github.com/neo-project/neo-devpack-dotnet/blob/5302960790302310647f539c9eb15190c5c004a9/src/Neo.SmartContract.Framework/Nep11Token.cs#L33-L35

**Comment by roman-khimov** [comment]
I think the behavior you get is correct wrt NEP-11 compliance, bad ID -> exception happens.

**Comment by cschuchardt88** [comment]
I agree, but i think the error message should be more informational. Should indicates something is wrong with `tokenId`. Currently it indicates that `StdLib.Deserialize` is the problem.

**Comment by cschuchardt88** [comment]
@Jim8y Please don't forget this issue. Only half is done.
