### ISSUE TITLE
Distribute neon as a .NET Global Tool

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#82]
the current model of distributing the NEON compiler requires many steps for the developer. .NET Core supports [global tools](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) which are easy to install and automatically are added to the path. Basically, all the developer would have to do would be 

``` shell
$ dotnet tool install -g Neo.Compiler.MSIL
```

we might also want to change the package name to just "neon"

**Comment by erikzhang** [comment]
It's a good idea!

**Comment by shargon** [comment]
i like it

**Comment by devhawk** [comment]
I'm going to make a series of changes to enable NEON to target NEO 2 and 3 + the generate debug info for neo-debugger. I will do enable NEON to be a global tool as part of that work

**Comment by devhawk** [comment]
FYI, I am going to do this w/o the changes to enable targeting Neo 2 and 3 from a single NEON exe

**Comment by erikzhang** [comment]
I have tried to publish with `/p:PublishSingleFile=true` and `/p:PublishTrimmed=true`, but it still generates huge exe.

**Comment by devhawk** [comment]
I just built [my soon-to-pr fork](https://github.com/devhawk/neo-devpack-dotnet/tree/devhawk/neonGlobalTool) locally and the resulting nupkg is about 300kb.
