### ISSUE TITLE
Automatically call "Serialize" in Put method (add method overloading to Serialize to support objects)

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-devpack-dotnet#84]
Hi,
For a better experience, I think our Storage.Put(key, value) should automatically call .Serialize() if we send an object.
At least the version I have here, it only accepts byte[], meaning we have to call Serialize manually.

**Comment by shargon** [comment]
Auto serialize, but what about deserialization? you need to provide both or is a bad design

**Comment by lock9** [comment]
@shargon  but I don't think it is possible to overload the method if we don't add new parameters. How do you plan to solve this? I think we need to leave all issues with at least 2 days in the design phase otherwise we may face these problems.

**Comment by igormcoelho** [comment]
We can provide both @shargon, it's just a Storage.Get<T> where user specifies the type.

**Comment by shargon** [comment]
but this will work in the compiler?

**Comment by igormcoelho** [comment]
Its not a compiler "thing".. both cases are just C# syntactic sugar for the underlying Serialize calls. The serialization is handled by annotation on top of the struct, and a method call. This method call be implicit in my opinion.

**Comment by lock9** [comment]
Ok @igormcoelho , I'm good with that:
Auto "serialize" and being able to use `Storage.Get<T>`
I'm moving this to ready to implement since more than 2 days have passed and it looks decided

**Comment by shargon** [comment]
And what's happen if i store an `int`, and read it as `get<MyClass>` ?

**Comment by igormcoelho** [comment]
for `int`, `long`, `short`, we should treat like `BigInteger`, and invoke its serialization/deserialization.
