### ISSUE TITLE
Remove `Runtime.Notify`

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-devpack-dotnet#843]
You should just remove `Runtime.Notify` its useless now. Or have it add the name to contract manifest.

Get error `Inner InvalidOperationException: Event 'SayHello3' does not exist.`

### Contract
```csharp
public class EventContract : SmartContract
{
    public delegate void OnSayHelloDelegate(string message);

    [DisplayName("SayHello1")]
    public static event OnSayHelloDelegate OnSayHello;

    [DisplayName("SayHello2")]
    public static event Action<string> SayHello;

    public static void Main()
    {
        OnSayHello("Hello, alice");

        SayHello("Hello, bob");

        Runtime.Notify("SayHello3", new[] { "Hello, joe" }); // crash
    }
}
```

**Comment by vncoelho** [comment]
Perhaps that is right to do

**Comment by Jim8y** [comment]
@shargon how do you think? I think this is a bug maybe, i have asked Erik for his opinion, but get no response.
maybe we should vote to make a decision? @vncoelho @roman-khimov

**Comment by Jim8y** [comment]
here https://github.com/neo-project/neo/issues/1879 as proposed by @roman-khimov  and completed by @erikzhang . But the problem is we allow user to use it in the syntax level, but not allowing it in the contract level. An annoying step to increase the bar of contract development.

**Comment by Jim8y** [comment]
![Screenshot 2023-12-23 at 12 11 45 PM](https://github.com/neo-project/neo-devpack-dotnet/assets/10189511/224dec0a-cf0c-462d-b7a1-09f5e22eaab6)

Now updated the contract analyzer to check the `notify` name with id NC4019

**Comment by cschuchardt88** [comment]
What if i did or want to do:
```csharp
public static void SayHelloTo(string eventName, string name)
{
    Runtime.Notify(eventName, new[] { $"Hello, {name}" });
}
```

Also what about the parameters? Do you check though too against manifest?

**Comment by Jim8y** [comment]
can be added.

**Comment by shargon** [comment]
I think that is a bug, seems good

**Comment by cschuchardt88** [comment]
@Jim8y Why not have `Runtime.Notify` event name be added to the manifest if it doesn't exists in the contract? Because you have to compile the contract in order to `deploy` or `update`.

**Comment by roman-khimov** [comment]
> Runtime.Notify event name be added to the manifest if it doesn't exist in the contract?

You can't do it for every possible `Runtime.Notify()` invocation, that's exactly your example with `Runtime.Notify(someVar, ...)`. If event name is a constant and if you exactly know all types of all parameters, that can be done (like in https://github.com/nspcc-dev/neo-go/pull/3008 with `--guess-eventtypes`), but not in general case. So requiring event specification of some kind (https://docs.neo.org/docs/en-us/develop/write/basics.html#events is C# probably) is perfectly fine and since this example is about event, it should just have one.

**Comment by Jim8y** [comment]
@shargon @roman-khimov , lets vote whether we ban Notify from contract developer. I think it is uselss now without allowing arbitary notification as user can use event directly.

**Comment by roman-khimov** [comment]
You can't ban Notify! How would you make a NEP-17 contract without it?

**Comment by Jim8y** [comment]
then any idea of solving the issue that notify become a trap now?
