### ISSUE TITLE
Add Math.Round

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-devpack-dotnet#844]
Add `Math.Round` for types `BigInteger`, `double`, `float`, `decimal`

```
Error	NC1002	Unknown method: System.Math.Round(double)
```

**Comment by Jim8y** [comment]
no double float decimal types are allowed

**Comment by cschuchardt88** [comment]
All it is byte data. For example if i had `124327789` as `BigInteger`, which really `1.24327789` some kind of rounding would be nice.  You can do it in binary. Its not that hard. See https://en.wikipedia.org/wiki/IEEE_754

The representation of `1.2432778910` is actually `00111111100111110010001110111011` as a single precision `IEEE 754` floating point number in binary.

This is made up of three parts:

1. The sign bit (`0` indicating it is positive)
1. The exponent (`01111111` which is `127`) giving <code>2<sup>127-127</sup></code> coming out to be `20`
1. The mantissa (`00111110010001110111011`) which has a leading `1` implicit.
1. This gives us <code>+2<sup>0</sup> * 1.00111110010001110111011</code> which then gives you your number. If you look at the first couple bits there of <code>1.0011111<sub>2</sub></code> you will see that this is rather close to <code>1.25<sub>10</sub></code> or <code>1.01<sub>2</sub></code>.

**Comment by cschuchardt88** [comment]
So now you know how to store it. You can add interoperability _(native smart contract)_ to do all the math stuff for `double`, `float`, `decimal`

**Comment by Jim8y** [comment]
wait, i mean why would we bother floating point operations if we dont support them at all?

**Comment by cschuchardt88** [comment]
The reason is to round some data. You can't round `124327789` _(`1.24327789`)_ in its' form unless, you do a lot of expensive math operations. Like above comment on `IEEE 754`. It's just exponent math. Well if you add rounding you can add floating points at same time. Because the way I look it, if you can have `sign` on integers than you can easily add floating points in that equation. Also `IEEE 754` does support up to 256-bit floating points.

**Comment by Jim8y** [comment]
i am lost here, not supporting floating point is one of the fundamental feature of smart contract and we will not add support it, why you always mention floating point here?

**Comment by cschuchardt88** [comment]
> why you always mention floating point here?

Nevermind I'll just do it in dapp programming language.

By the way the reason why smart contracts don't support floating points is:
1. Imagine a 256-bit decimal for currency? `100.8375897235375897237598723952375923758923795923875982398579823`, it's all about making money. It's funny, so you can slow down the rate at which the value of the currency increases. So this way people will spend money, thats why prices swing so big.
1. It's cheaper for storage.
1. It's cheaper CPU cost for `opcodes` on non-floating points. _(but we use encryption; not so cheap; hey `Elliptic-curve`)_

At the end of the day it's just comes down to cost!!! Because you have `vm` cost both resources and money, along with developing and maintaining it, as well as compilers, that need to written in C++ to get use out of the CPUs opcodes for floating points. I mean i can go on forever....

All im saying is if i can calculate it in a contract, why can't you add it. Now im question why have interoperability at all.

**Comment by Jim8y** [comment]
Close as we will not add support to any method related to floating point.
