### ISSUE TITLE
Make `Runtime.ScriptContainer` return a Transaction object

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-devpack-dotnet#858]
Hi,

Problem:
The `Runtime.ScriptContainer` is returning a generic `object`. This demands users to cast it into a transaction every time they want to use it:
`var tx = (Transaction)Runtime.ScriptContainer;`

Proposed Solution:
Since the ScriptContainer will always be a Transaction, the smart contract compiler can return a Transaction type instead of object. 
Result:
`var tx = Runtime.ScriptContainer;`

**Comment by Jim8y** [comment]
we can add a method to get the transaction instead.

**Comment by lock9** [comment]
@Jim8y I've spoken to Roman, who confirmed that it will always return a transaction. I'm not against adding a new interface, but it would be ok to change the existing one

**Comment by cschuchardt88** [comment]
@lock9  You can just add the following code to your contract. It the same we are going to use. `CONVERT` opcode isn't required or generated. `System.Runtime.GetScriptContainer` in the `ApplicationEngine` converts for free for whatever the `IVerifiable` type is. In this case it's `Transaction`.

```json
[Syscall("System.Runtime.GetScriptContainer")]
public static extern Transaction GetTransaction();
```

**Comment by shargon** [comment]
> @Jim8y I've spoken to Roman, who confirmed that it will always return a transaction. I'm not against adding a new interface, but it would be ok to change the existing one. I believe that GetTransaction can be misleading. The GetTransaction is already present elsewhere (probably at the ledger interface)

A consensus wallet that try to verify the block will return the block

**Comment by roman-khimov** [comment]
Block verification is a simple multisig script that doesn't call `GetScriptContainer`. You can't run your code (created with devpack) in this context. Same goes for OnPersist/PostPersist, no user-created code runs there.

**Comment by Jim8y** [comment]
Before i open this pr, I have searched everywhere, exactly as @roman-khimov said, container is only used for transaction.

**Comment by shargon** [comment]
> Block verification is a simple multisig script that doesn't call `GetScriptContainer`. You can't run your code (created with devpack) in this context. Same goes for OnPersist/PostPersist, no user-created code runs there.

That's true, currently we only use a multisign for blocks

**Comment by roman-khimov** [comment]
And even if we'd like to change it for whatever reason (_highly_ unlikely, but we technically can have anything in this script) that'd be code created by the system (CNs), not something created by devpack user.
