### ISSUE TITLE
Add support to 'long' switch statements

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-devpack-dotnet#86]
There is a problem with the `switch` instruction, it seems that works if we have less entries than 6, with more, it doesn't works.

I made a pull request for test this issue at, https://github.com/neo-project/neo-devpack-dotnet/pull/87

if you comment some entries, the test will work

**Comment by erikzhang** [comment]
It is because the CLR uses hash table to optimize the `switch` segment. And there is no native support for that hash table in NeoVM.

**Comment by shargon** [comment]
There is not possible to convert this hash table into a jump table?

Pseudocode:

```csharp
// With hash table
hash= [ 0x0a, 0x0b, 0x0c ] 
JMP(hash[2]);

// Without hash table

0x00 NOP
0x01 JMP 0x0a
0x02 JMP 0x0b
0x03 JMP 0x0c

JMP 0x02


```

**Comment by shargon** [comment]
dnSpy decompile the source as:
```csharp
using System;
using Neo.SmartContract.Framework;

namespace Neo.Compiler.MSIL.TestClasses
{
	// Token: 0x02000017 RID: 23
	internal class Contract_Switch : SmartContract
	{
		// Token: 0x0600005E RID: 94 RVA: 0x00003C78 File Offset: 0x00001E78
		public static object Main(string method, object[] args)
		{
			if (method != null)
			{
				uint num = <PrivateImplementationDetails>.ComputeStringHash(method);
				if (num <= 518729469u)
				{
					if (num <= 434841374u)
					{
						if (num <= 350953279u)
						{
							if (num != 334175660u)
							{
								if (num == 350953279u)
								{
									if (method == "19")
									{
										return 20;
									}
								}
							}
							else if (method == "18")
							{
								return 19;
							}
						}
						else if (num != 401286136u)
						{
							if (num != 418063755u)
							{
								if (num == 434841374u)
								{
									if (method == "16")
									{
										return 17;
									}
								}
							}
							else if (method == "15")
							{
								return 16;
							}
						}
						else if (method == "14")
						{
							return 15;
						}
					}
					else if (num <= 468396612u)
					{
						if (num != 451618993u)
						{
							if (num == 468396612u)
							{
								if (method == "10")
								{
									return 11;
								}
							}
						}
						else if (method == "17")
						{
							return 18;
						}
					}
					else if (num != 485174231u)
					{
						if (num != 501951850u)
						{
							if (num == 518729469u)
							{
								if (method == "13")
								{
									return 14;
								}
							}
						}
						else if (method == "12")
						{
							return 13;
						}
					}
					else if (method == "11")
					{
						return 12;
					}
				}
				else if (num <= 873244444u)
				{
					if (num <= 822911587u)
					{
						if (num != 806133968u)
						{
							if (num == 822911587u)
							{
								if (method == "4")
								{
									return 5;
								}
							}
						}
						else if (method == "5")
						{
							return 6;
						}
					}
					else if (num != 839689206u)
					{
						if (num != 856466825u)
						{
							if (num == 873244444u)
							{
								if (method == "1")
								{
									return 2;
								}
							}
						}
						else if (method == "6")
						{
							return 7;
						}
					}
					else if (method == "7")
					{
						return 8;
					}
				}
				else if (num <= 923577301u)
				{
					if (num != 890022063u)
					{
						if (num != 906799682u)
						{
							if (num == 923577301u)
							{
								if (method == "2")
								{
									return 3;
								}
							}
						}
						else if (method == "3")
						{
							return 4;
						}
					}
					else if (method == "0")
					{
						return 1;
					}
				}
				else if (num != 1007465396u)
				{
					if (num != 1024243015u)
					{
						if (num == 2381486463u)
						{
							if (method == "20")
							{
								return 21;
							}
						}
					}
					else if (method == "8")
					{
						return 9;
					}
				}
				else if (method == "9")
				{
					return 10;
				}
			}
			return 99;
		}
	}
}
```

**Comment by erikzhang** [comment]
You need to implement `<PrivateImplementationDetails>.ComputeStringHash()` in NeoVM to support `switch`.

**Comment by shargon** [comment]
@lightszero do you think that this is feasible?

**Comment by lightszero** [comment]
as eric said. ComputeStringHash is a sad story.

> swtich xxx
> {
>   case "aa":
> }

I can't got "aa" form IL in current convert solution(current solution is use Mono.cecil to conv IL -> AVM).

add switch support need to use another cconvert solution(maybe add some rosyln part).

**Comment by erikzhang** [comment]
@lightszero We can add `ComputeStringHash()` on Interop.

**Comment by lightszero** [comment]
C# 's stringhash is different with java,so we need many stringhash interop.

**Comment by shargon** [comment]
I understand the problem ... if we receive a compilation error, is enough to me

**Comment by shargon** [comment]
@lightszero could you check why here https://github.com/neo-project/neo-devpack-dotnet/pull/87/files#diff-38aefe612b09c5f19d1ec205b952b39cR19 is not throwed any exception?

**Comment by shargon** [comment]
And is possible to generate this method on runtime, without a syscall, and just call it?

```csharp
internal static uint ComputeStringHash(string s)
	{
		uint num;
		if (s != null)
		{
			num = 2166136261u;
			for (int i = 0; i < s.Length; i++)
			{
				num = ((uint)s.get_Chars(i) ^ num) * 16777619u;
			}
		}
		return num;
	}
```

**Comment by shargon** [comment]
@lightszero this is something crazy?

Try to detect the call, and redirect to another one loaded in the framework
https://github.com/shargon/neo-devpack-dotnet/pull/2

**Comment by erikzhang** [comment]
Calling the generated `ComputeStringHash()` in the runtime is too expensive.

**Comment by shargon** [comment]
I agree with you @erikzhang
Changed https://github.com/neo-project/neo-devpack-dotnet/pull/87 to detect and improve the exception and finished the unit tests to make it easy for developers to discover why this does not work

**Comment by lock9** [comment]
@shargon  will #87 close this issue?

**Comment by lightszero** [comment]
we can add some simple method for switch.
after of all,we can touch the contract c# sourcecode.
If we can't get info from IL,then we got it from sourcecode.
we can got all string in sourcecode.and save all of it.

then we got a Hash in IL,we can knwon the string.

**Comment by lightszero** [comment]
no need to touch contract c# sourcecode
I study IL switch pattern，how it can work after delete hashpart。

**Comment by shargon** [comment]
Thanks @lightszero ! amazing work!

**Comment by devhawk** [comment]
Can we port this to master-2.x?

**Comment by shargon** [comment]
Yes, I think so

**Comment by shargon** [comment]
Also, this issue should be closed and create a new one https://github.com/neo-project/neo-devpack-dotnet/issues/157
