### ISSUE TITLE
Add support to Array.Empty

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-devpack-dotnet#861]
The compiler does not support the following line:

`Array.Empty<object>();`

Would it be possible to add support to it? The IDE doesn't show any errors, it's only possible to know that it doesn't work after trying to compile it:

Failed to compile:
`EXEC : error NC1002: Unknown method: System.Array.Empty<object>() `

This will work but the IDE doesn't like it (shows a warning):
`new object[] { };`

`Avoid unnecessary zero-length array allocations.  Use Array.Empty<object>() instead.[CA1825](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1825)`

**Comment by cschuchardt88** [comment]
Have you tried
```csharp
new object[];
```
