### ISSUE TITLE
StorageMap optimizations

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-devpack-dotnet#88]
In every get, put, or delete, we convert the `string` to `byte[]` and concat it with the prefix `0x00`, is better to concat this at the initialization, only once.

Also should be added two overloads, for allow one `byte` and `byte[]` parameters

https://github.com/neo-project/neo-devpack-dotnet/blob/cbb3ca1518a7d3757456cced98f1d45b0e2b1b02/src/Neo.SmartContract.Framework/Services/Neo/Helper.cs#L18-L72

**Comment by erikzhang** [comment]
Why we need those `0`s?

**Comment by shargon** [comment]
We don't need it, i just copied it, but we can remove this 0 too

**Comment by shargon** [comment]
Shall i remove these 0s?

**Comment by erikzhang** [comment]
If they are useless, we should remove them.

**Comment by shargon** [comment]
Done
