### ISSUE TITLE
Create a TestEngine

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-devpack-dotnet#889]
We have a problem creating unit tests, I'm going to make a testEngine to facilitate the testing of smart contracts.

- [x] #890 . It will create a dll with the contract to be able to call it by code
- [x] #898 
- [x] #893
- [x] #904
- [x] #908 
- [x] #936
- [x] #937

Doc:
- https://github.com/neo-project/neo-devpack-dotnet/blob/master/src/Neo.SmartContract.Testing/README.md

Bugs found with this engine:
- https://github.com/neo-project/neo-devpack-dotnet/pull/895
- https://github.com/neo-project/neo-devpack-dotnet/pull/891
- https://github.com/neo-project/neo/issues/3145
- https://github.com/neo-project/neo-devpack-dotnet/pull/938

**Comment by cschuchardt88** [comment]
I will be creating an `DebugApplicationEngine`. After my `TraceApplicationEngine`. Just keep that in mind.

**Comment by shargon** [comment]
> I will be creating an `DebugApplicationEngine`. After my `TraceApplicationEngine`. Just keep that in mind.

The underlying engine could be changed in a future in order to be more verbose.

**Comment by cschuchardt88** [comment]
> > I will be creating an `DebugApplicationEngine`. After my `TraceApplicationEngine`. Just keep that in mind.
> 
> The underlying engine could be changed in a future easily in order to be more verbose.

I already did that. Im not changing `ApplicationEngine`. I am however replacing it by doing `ApplicationEngine.Provider = new TraceApplicationEngine());`

**Comment by shargon** [comment]
> I don't know why you reinventing the wheel again. When we have already made it.

I'm tired of seeing projects in neo without **any unit tests**, it's not easy to do them, show me a single project that has them, I think this wheel is not even being reinvented, if it is even designed.

**Comment by cschuchardt88** [comment]
Your misunderstanding it. I explained it in correctly. 

The `TestEngine` you are creating. Can be done with ease with `IApplicationEngineProvider`.  All I am saying is build your Engine with that Interface. So you can plugin/hook into the `ApplicationEngine` `protected` or `virtual` methods for getting all the VMs information. I don't think I need to tell you the information you can get from `ApplicationEngine`. But this would be the real big test. Where you can test on `mainnet` or `testnet` without problems. I been working on `TraceApplicationEngine` for about a day. And was saying no one should reinvent all the functionality that `ApplicationEngine` has already. We have an `Engine` Its called `ApplicationEngine`. You should make `TestApplicationEngine` or `ContractApplicationEngine`. If that makes sense.

**Comment by roman-khimov** [comment]
IIUC that'd be something similar to https://pkg.go.dev/github.com/nspcc-dev/neo-go/pkg/neotest or https://neow3j.io/#/neo-n3/smart_contract_development/testing. But both have some real or almost real ledger behind, so invocations are real transactions packed into some blocks and processed in a regular way. Can you you provide more details on how DLL-packed contracts will work here?

**Comment by shargon** [comment]
> IIUC that'd be something similar to https://pkg.go.dev/github.com/nspcc-dev/neo-go/pkg/neotest or https://neow3j.io/#/neo-n3/smart_contract_development/testing. But both have some real or almost real ledger behind, so invocations are real transactions packed into some blocks and processed in a regular way. Can you you provide more details on how DLL-packed contracts will work here?

The problem that we have been encountering throughout all the contracts reviewed is mainly the same, the contracts have not been tested, and the lack of unit tests.

What I am doing is the ability to generate some "artifacts" abstract class extracted from `NefFile`, in this way the testing is not limited to contracts made in C#, these artifacts generate a valid C# code descriptive of the Abi, and through mocks, I intend convert types between VM<>dotnet to facilitate calling and testing contracts.

The initial idea (it may evolve in a future version) is to test without generating a transaction, so if you want to simulate two transactions you would have to do something like this:

```csharp
var walletA= new UInt160("a");
var walletA= new UInt160("b");
TestEngine engine=new ();

var contract = engine.Deploy<MyContract>();

engine.Signer= walletA;
contract.Mint();

engine.Signer= walletB;
Assert.IsFalse(contract.Transfer(walletA,walletB,1)); // no signed by a

engine.Signer= walletA;
Assert.IsTrue(contract.Transfer(walletA,walletB,1));
```

**Comment by shargon** [comment]
Here you can see how it will work:

https://github.com/neo-project/neo-devpack-dotnet/blob/f00d32a7eae7b739cf512f9c8d735ad84af38f19/tests/Neo.SmartContract.Testing.UnitTests/NativeArtifactsTests.cs

**Comment by Jim8y** [comment]
would be much better if you had provided a detailed introduction on what you are trying to do, and how it is supposed to work.

**Comment by cschuchardt88** [comment]
> would be much better if you had provided a detailed introduction on what you are trying to do, and how it is supposed to work.

@shargon  Yes we need more information. So you dont waste everyone's time, including yours.

**Comment by shargon** [comment]
> would be much better if you had provided a detailed introduction on what you are trying to do, and how it is supposed to work.

Got it, next time I will do that. My goal is to make it easy unit tests for any smart contract, because trust me, there's a lack of this everywhere.

**Comment by cschuchardt88** [comment]
> > would be much better if you had provided a detailed introduction on what you are trying to do, and how it is supposed to work.
> 
> Got it, next time I will do that. My goal is to make it easy unit tests for any smart contract, because trust me, there's a lack of this everywhere.

That is fine. How are we to use it? To do we build tests now? How do we setup the environment? What is required of a test? Whats the convention of the API? How files and configuration laid out?

**Comment by shargon** [comment]
> That is fine. How are we to use it? How do we build tests now? How do we setup the environment? What is required of a test? Whats the convention of the API? How are files and configuration laid out?

I will write a Readme.md explaining the new testing environment

**Comment by cschuchardt88** [comment]
@shargon can you add checks points to your engine?

**Comment by cschuchardt88** [comment]
Also can we have in binary file format? If not already.

**Comment by shargon** [comment]
> Also can we have in binary file format? If not already.

Of course, it could be faster

**Comment by cschuchardt88** [comment]
> > Also can we have in binary file format? If not already.
> 
> Of course, it could be faster

I mean as a log binary file.

**Comment by shargon** [comment]
I think that the testEngine is finished, let's move to the next step https://github.com/neo-project/neo-devpack-dotnet/issues/949

**Comment by shargon** [comment]
I think that the testEngine is finished, let's move to the next step https://github.com/neo-project/neo-devpack-dotnet/issues/949
