### ISSUE TITLE
Release workflow doesn't work

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-devpack-dotnet#905]
https://github.com/neo-project/neo-devpack-dotnet/blob/120d87683f3e851c0f3562485b3e7aac7b66b005/.github/workflows/release.yml#L1

It seems that is not working, workflow log always fails

**Comment by cschuchardt88** [comment]
What are trying to accomplish with this `yml`?

**Comment by cschuchardt88** [comment]
@shargon wrong directory.

should be `.github/release.yml`

**Comment by shargon** [comment]
Could someone move it? If don't I will do tomorrow
