### ISSUE TITLE
TestEngine: Coverage and test current smart contracts

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-devpack-dotnet#949]
After https://github.com/neo-project/neo-devpack-dotnet/issues/889

We need to continue with the following tasks:

- [x] #908 
- [x] https://github.com/neo-project/neo-devpack-dotnet/pull/950
- [x] https://github.com/neo-project/neo-devpack-dotnet/pull/956
- [x] https://github.com/neo-project/neo-devpack-dotnet/pull/963
- [x] https://github.com/neo-project/neo-devpack-dotnet/pull/968
- [x] Migrate `Neo.Compiler.CSharp.UnitTests` and remove old `TestEngine`.

**Comment by Jim8y** [comment]
completed
