### ISSUE TITLE
Can't Compile Neo Burger Contract: '(95,32): error NC3003: Duplicate method key: transfer,4.'

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-devpack-dotnet#989]
Hi,

The title says it all.  I'm unable to compile the Neo Burger contract. 
I've copied the code from here: https://github.com/neoburger/code/blob/main/BurgerNEO.cs

When I try to compile it, I get:
```
(95,32): error NC3003: Duplicate method key: transfer,4.
```

This is my line 95:
```csharp
public static new bool Transfer(UInt160 from, UInt160 to, BigInteger amount, object data)
```

I'm using NCCS / Neo Framework 3.6.2

**Comment by shargon** [comment]
Maybe it should be an override instead of a static new

**Comment by lock9** [comment]
I'm going to test that. I've just copied the code and wondered why it didn't work.  Using `override` is not possible:
<img width="749" alt="Screenshot 2024-03-11 at 10 57 42" src="https://github.com/neo-project/neo-devpack-dotnet/assets/38396062/9fc661cf-729d-4b41-82fd-390f74ad2ebc">

Either the code was committed with errors or the compiler introduced breaking changes. Any chances you can check if it's not a bug?

**Comment by shargon** [comment]
remove the `static` and the `new`, and use override, it works?

**Comment by Jim8y** [comment]
Burger is using old compiler, the name conflicts rule has being updated.

**Comment by roman-khimov** [comment]
But why is it incompatible? Just imagine everyone updating compiler now and hitting the same issue.

**Comment by lock9** [comment]
In this case, I will assume that it's the developer's responsibility to update the code. Is there any risk of using an older compiler?

**Comment by shargon** [comment]
Agree with @Jim8y , is using a different Token base class, it's incompatible with the new code

**Comment by Jim8y** [comment]
> In this case, I will assume that it's the developer's responsibility to update the code. Is there any risk of using an older compiler?

The code is written by alibaba,,,,dont trust his source code, cause he checked the compiled opcode and manifest line by line and modify it manually to avoid any issue in the contract.

**Comment by vang1ong7ang** [comment]
> NeoBurger is a project from the very early age of neo3.
>
> The compiler and toolkits at that time were not developed well and were not compatible with the latest version.
>
> If you want to know how neoburger's code is compiled, view [Github Workflow YML file](.github/workflows/dotnet.yml).
>
> Due to the limitations of the toolkits at that time, this code used some tricky skills, so it is **NOT** recommended that the new version of the compiler restore its compatibility.
>
> In order to keep consistency with the running smart contract code of NeoBurger on the mainnet, the code will not be switched to the new version of the compiler for the time being.

*from <https://github.com/neoburger/code/blob/ea55582987ba7a36d6332bb2400163133431f832/README.md?plain=1#L4-L15>*

**Comment by Hecate2** [comment]
In `neo-devpack-dotnet/src/Neo.Compiler.CSharp/CompilationContext.cs` find codes like this
```csharp
if (methodsExported.Any(u => u.Name == method.Name && u.Parameters.Length == method.Parameters.Length))
    throw new CompilationException(symbol, DiagnosticId.MethodNameConflict, $"Duplicate method key: {method.Name},{method.Parameters.Length}.");
```
Replace it with
```csharp
                //if (methodsExported.Any(u => u.Name == method.Name && u.Parameters.Length == method.Parameters.Length))
                //    throw new CompilationException(symbol, DiagnosticId.MethodNameConflict, $"Duplicate method key: {method.Name},{method.Parameters.Length}.");
                AbiMethod? foundMethod = methodsExported.Where(u => u.Name == method.Name && u.Parameters.Length == method.Parameters.Length).FirstOrDefault();
                if (foundMethod is not null)
                    methodsExported.Remove(foundMethod);
```
