### ISSUE TITLE
NCCS: Helper.GetPatternType() not supported ByteString and BigInteger

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-devpack-dotnet#992]
https://github.com/neo-project/neo-devpack-dotnet/blob/4661dd2c28ea23a3ed1aa3082db0c1ca340ae81d/src/Neo.Compiler.CSharp/Helper.cs#L126-L137

The code above, looks like it supports `ByteString` and `BigInteger`, but in fact, if it's written this way in the contract, he'll report an error somewhere else.

```c#
public void M(object o1)
{
    switch (o1)
    {
        case byte[]: break;       // Compile Successfully
        case string: break;       // Compile Successfully
        case bool: break;         // Compile Successfully
        case ByteString: break;   //Compile Failure
        case BigInteger: break;   //Compile Failure
    }
}
```

<img width="1431" alt="image" src="https://github.com/neo-project/neo-devpack-dotnet/assets/6295602/4482c833-2773-4244-a4ef-38913ca53948">
This method(ConvertIdentifierNameExpression) throws an exception

**Comment by Hecate2** [comment]
I think it is not supported by the syntax analyzer [roslyn](https://github.com/dotnet/roslyn/blob/f520a73885f163f6b9f08b9c64eb0fa381ca60ed/src/Compilers/CSharp/Portable/Syntax/Syntax.xml#L2904-L2950) to judge whether `o1` is of type `Class` by writing `case Class:`.
By writing `case ByteString:`, we require the variable `o1` to equal the class `ByteString`.
`case ByteString _:` is OK

**Comment by shargon** [comment]
@chenzhitong could you create the unit test contract where it fail in order to fix it easier?
