### ISSUE TITLE
Neo Smart Contract Templates

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-devpack-dotnet#997]
@shargon 

Is the version correct?

https://github.com/neo-project/neo-devpack-dotnet/blob/31beddea0632c412da910cd440d5b79232c6202d/src/Neo.SmartContract.Template/templates/neocontractowner/.template.config/template.json#L20

https://github.com/neo-project/neo-devpack-dotnet/blob/31beddea0632c412da910cd440d5b79232c6202d/src/Neo.SmartContract.Template/templates/neocontractnep17/.template.config/template.json#L20

https://github.com/neo-project/neo-devpack-dotnet/blob/31beddea0632c412da910cd440d5b79232c6202d/src/Neo.SmartContract.Template/templates/neocontractoracle/.template.config/template.json#L20

**Comment by shargon** [comment]
we can wait for the next release (3.6.7) to change it.

**Comment by cschuchardt88** [comment]
these still are not changed

**Comment by shargon** [comment]
we can use the last one
